### ISSUE TITLE
GUI - when removing two apps, the second on fails with a syncthing error.

### ISSUE THREAD

**Issue by rileysaurus** [kalabox/kalabox#998] opened 2016-02-12 01:23 UTC
Error dispatching event listeners [post-app-uninstall]: Unexpected error while waiting for syncthing http://127.0.0.1:60008 to start.: operation timed out

**Comment by pirog** [comment] 2016-02-12 18:40
Can you consistently replicate this?

**Comment by pirog** [comment] 2016-03-23 22:14
@rileysaurus does this seem to be the same thing as #1149?

**Comment by reynoldsalec** [comment] 2016-04-12 05:30
Experienced the same issue when removing two apps at the same time.

**Comment by pirog** [comment] 2016-04-18 01:29
Going to close this as duplicate of #1228

**Closed by pirog** 2016-04-18 01:29 UTC
Labels: duplicate
