### ISSUE TITLE
"Cannot read property 'mysql_command' of undefined"

### ISSUE THREAD

**Issue by dalehgeist** [kalabox/kalabox#1431] opened 2016-07-01 21:46 UTC
Bug Report
==========

I'm running v0.12.0-beta.1 on Mac OSX 10.11.5

I had not previously installed Kalabox.

From the cli I tried to kbox push both code and database to dev. The code pushed successfully. During the database push I got the following error: "Cannot read property 'mysql_command' of undefined" (The error message listed several paths, which I will paste below.) 

I found issue #1035 which seemed to relate to that. In that issue, an update was recommended to Terminus. I performed the update. Same result. My Terminus version is 0.11.2. Terminus script: Terminus. 

Here is the full error message:
```
Cannot read property 'mysql_command' of undefined
TypeError: Cannot read property 'mysql_command' of undefined
    at /Users/dalegeist/.kalabox/apps/pegasusnapa/plugins/kalabox-plugin-pantheon/lib/push.js:126:17
From previous event:
    at Object.pushDB (/Users/dalegeist/.kalabox/apps/pegasusnapa/plugins/kalabox-plugin-pantheon/lib/push.js:112:6)
    at /Users/dalegeist/.kalabox/apps/pegasusnapa/plugins/kalabox-plugin-pantheon/lib/tasks.js:338:29
    at process._tickCallback (node.js:917:13)
From previous event:
    at null.completed (/Users/dalegeist/.kalabox/apps/pegasusnapa/plugins/kalabox-plugin-pantheon/lib/tasks.js:336:12)
    at PromptUI.onCompletion (/Users/dalegeist/.kalabox/apps/pegasusnapa/node_modules/inquirer/lib/ui/prompt.js:56:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/Users/dalegeist/.kalabox/apps/pegasusnapa/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1826:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/dalegeist/.kalabox/apps/pegasusnapa/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1763:14)
    at AnonymousObserver.tryCatcher (/Users/dalegeist/.kalabox/apps/pegasusnapa/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:537:29)
    at AutoDetachObserverPrototype.completed (/Users/dalegeist/.kalabox/apps/pegasusnapa/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5435:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/dalegeist/.kalabox/apps/pegasusnapa/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1763:14)
    at InnerObserver.onCompleted (/Users/dalegeist/.kalabox/apps/pegasusnapa/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:2885:65)
    at InnerObserver.tryCatcher (/Users/dalegeist/.kalabox/apps/pegasusnapa/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:537:29)
    at AutoDetachObserverPrototype.completed (/Users/dalegeist/.kalabox/apps/pegasusnapa/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5435:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/dalegeist/.kalabox/apps/pegasusnapa/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1763:14)
    at AutoDetachObserver.tryCatcher (/Users/dalegeist/.kalabox/apps/pegasusnapa/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:537:29)
    at AutoDetachObserverPrototype.completed (/Users/dalegeist/.kalabox/apps/pegasusnapa/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5435:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/dalegeist/.kalabox/apps/pegasusnapa/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1763:14)
    at InnerObserver.onCompleted (/Users/dalegeist/.kalabox/apps/pegasusnapa/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:2885:65)
    at InnerObserver.tryCatcher (/Users/dalegeist/.kalabox/apps/pegasusnapa/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:537:29)
    at AutoDetachObserverPrototype.completed (/Users/dalegeist/.kalabox/apps/pegasusnapa/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5435:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/dalegeist/.kalabox/apps/pegasusnapa/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1763:14)
    at AutoDetachObserver.tryCatcher (/Users/dalegeist/.kalabox/apps/pegasusnapa/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:537:29)

```

**Comment by dalehgeist** [comment] 2016-07-01 21:47
Note: the first time I did a kbox push, the database pushed successfully. This happened the second time I tried it.

**Comment by pirog** [comment] 2016-07-02 22:22
Interesting. 

In your app you should be able to see your terminus cache over at `config/terminus` i would try removing that cache and see if you are able to push successfully. 

Have you looked over in the terminus issue queue for similar errors?

**Comment by dalehgeist** [comment] 2016-07-07 21:01
Thanks, @pirog . I looked in config/terminus in my app and there is nothing that looks like a cache file. Here are the files in there: 
- b16571fd-42fc-4467-a165-530f072cb098_sites -- holds the Pantheon info
- latest_release -- came with my update
- php.ini
- session -- unix executable
- tokens folder -- empty

Nothing like this appears in the terminus issue query.

**Comment by pirog** [comment] 2016-07-08 18:55
i would try removing that `b16571fd-42fc-4467-a165-530f072cb098_sites` and see if that allows you to run the command you desire

**Comment by dalehgeist** [comment] 2016-07-08 22:35
Nope. Thanks for the suggestion, though. The error message makes it look like it's something in push.js that's not finding what it needs.

**Comment by pirog** [comment] 2016-07-08 22:50
@dalehgeist i would feel that way too except that it worked fine the first time you ran it right? I'm wondering if the issue is upstream in Pantheons terminus project.

**Comment by pirog** [comment] 2016-07-21 05:09
@dalehgeist 

I think this has been resolved in our hot off the press release. Check that out over at
https://github.com/kalabox/kalabox/releases/tag/v0.13.0-beta.2 (we haven't updated the download on kalabox.io yet) and def read the docs on how to [update your kalabox](http://docs.kalabox.io/en/stable/users/updating/)

If the issue persists please reopen this (or submit a new) issue!

**Closed by pirog** 2016-07-21 05:09 UTC
Labels: bug fix, pantheon app
