### ISSUE TITLE
Kalabox GUI does not get past loading screen on Windows

### ISSUE THREAD

**Issue by sandipsclarion** [kalabox/kalabox#1435] opened 2016-07-06 13:03 UTC
Tell us about your setup

What is your Kalabox version and operating system?
v0.12.0-beta1 on Windows 8.1 Eternprise*

Have you previously installed Kalabox? If so, what version?
Yes, I've installed kalabox-v0.12.0-beta

I face the issue with kalabox gui startup. some time it's start soon and some time just showing the message with starting window as per attached screenshot

![kalabox-startup](https://cloud.githubusercontent.com/assets/16461960/16618655/3e914b52-433f-11e6-94ec-c974764568c4.png)

please let me know why it is hapenning.
if anyone having solution please provide ASAP.

**Comment by pirog** [comment] 2016-07-07 18:57
Good to know. We are getting ready to roll out the 13-alpha2 and if this is not resolved in that maybe @reynoldsalec can give it a look see.

**Comment by reynoldsalec** [comment] 2016-07-07 19:23
@sandipsclarion & @jpilcher if you hit F12 during startup, are there any errors in the console?

Also curious if you go into VirtualBox, does the Kalabox2 Virtualmachine startup? Another way of testing this would be to see if `kbox up` and `kbox create drupal7` work on your machine.

**Comment by sandipsclarion** [comment] 2016-07-08 04:18
I verified that kalabox VM is running while above process is working.
I tried to run the site using kbox start command by running this command in project dir. it works.
the main issue is that we are not able to see GUI of kalabox.

**Comment by pirog** [comment] 2016-07-08 18:47
@sandipsclarion good to know. so the issue is just with the GUI launching? the CLI appears to work correctly?

**Comment by sandipsclarion** [comment] 2016-07-11 04:26
yes, CLI working proper

**Comment by jpilcher** [comment] 2016-07-11 16:57
@reynoldsalec Interesting, I don't appear to have a Kalabox2 image in VirtualBox. I can uninstall everything and try installing again. Any reason why the Kalabox2 image wouldn't be created?

**Comment by jpilcher** [comment] 2016-07-11 18:21
I reinstalled everything and now I have a Kalabox image in VirtualBox. It still won't start up via the GUI and when I run `kbox up` I get the bellow error.

```
Unhandled rejection VError: Failed after 5 retries. {"max":5,"backoff":500}: : code: 1err:Error getting IP address: Something went wrong running an SSH command!
command : ip addr show
err     : exit status 255
output  :

    at C:\Program Files\Kalabox\bin\lib\promise.js.jx:70:17
From previous event:
    at rec (C:\Program Files\Kalabox\bin\lib\promise.js.jx:56:13)
    at C:\Program Files\Kalabox\bin\lib\promise.js.jx:64:20
From previous event:
    at C:\Program Files\Kalabox\bin\lib\promise.js.jx:63:12
    at process._tickCallback (node.js:917:13)
```

**Comment by pirog** [comment] 2016-07-12 16:21
@jpilcher i assume you've tried to restart it with `kbox down` and then `kbox up`? Does that consistently produce the same result for you?

**Comment by macronomicus** [comment] 2016-07-20 21:16
Same on windows 10pro using gui wont go past the loading screen, the f12 error screen is blank & empty.
The cli works even better than ever so far though! :) I tend to prefer cli anyhow.
Im using version 0.13.0-alpha.1-21-g68cb2f3

**Comment by pirog** [comment] 2016-07-20 23:05
Good to know. We estimate the GUI bug is not that hard to lock down we just
haven't had a chance to do so yet. CLI should def be a lot better though so
glad to hear that!

**Comment by pirog** [comment] 2016-07-21 07:48
@reynoldsalec so using the latest `v0.13.0-beta.2` this fails... however if you run `grunt gui` for the same version it works fine... so i suspect there is something about the packaged gui vs the source that causes this.

**Comment by pirog** [comment] 2016-07-21 15:40
@reynoldsalec so i think this is getting hungup in `sites.get()` in `initialize.js`

**Comment by pirog** [comment] 2016-07-21 15:53
Hmmm scratch that... if i pkg the GUI on Windows it actually seems to work... major difference there is `x64` vs `ia32`

**Comment by pirog** [comment] 2016-07-21 16:18
Double scratch, if i `grunt pkg:gui` for either `x64` or `ia32` it works as expected on windows... so i guess there is something about appveyor that is messing this whole thing up.

**Comment by pirog** [comment] 2016-07-21 17:23
So final thoughts on this before i move on. I think this is purely on the install side of things and not an issue with the gui/cli code. I think we need to get the installer to sandbox the gui in its own directory for this to work. 

Going to assign this to myself.

**Closed** 2016-07-21 23:40 UTC
Labels: blocker, bug fix
