### ISSUE TITLE
Error purging partially installed apps

### ISSUE THREAD

**Issue by madeofpeople** [kalabox/kalabox#440] opened 2015-09-03 16:00 UTC
Sometimes an install doesn't go 100% through, but then to install successfully I need to purge the app and start anew.

But I get errors like below:
```
$ kbox uninstall -- --purge
info: DOCKER =>  Starting container kalabox_syncthing.
info: DOCKER =>  Container started. kalabox_syncthing

info: DOCKER =>  Removing container undefined. v=true, kill=false
ENOENT, no such file or directory '/Users/thiago/kalabox/XXXXX/.cids/data'
Error: ENOENT, no such file or directory '/Users/thiago/kalabox/XXXXX/.cids/data'
    at Error (native)
    at Object.fs.unlinkSync (evalmachine.<anonymous>:883:18)
    at /usr/local/lib/node_modules/kalabox/plugins/kalabox-core/tasks/uninstall.js:38:18
```

the errors vary based on where the install failed.

````
$ kbox uninstall -- --purge
EVENTS =>  Error dispatching event listeners [pre-uninstall].
Error: HTTP code is 500 which indicates error: server error - Cannot start container 7bdc283ff4a5b05d4e926078ed1371eea0644cdc74bcba46f8b62d43ff585d4f: Could not apply volumes of non-existent container "kb_XXX_data".

    at /usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:204:17
    at getCause (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:232:7)
    at Modem.buildPayload (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:203:5)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:179:14)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

is there a 'hard and unrepentant purge' or something similar?

**Comment by pirog** [comment] 2015-09-03 21:18
@madeofpeople going to mark this as a duplicate of #416 

WHICH YOU ALREADY OPENED BY THE WAY. :)

**Closed by pirog** 2015-09-03 21:18 UTC
Labels: duplicate

**Comment by madeofpeople** [comment] 2015-09-03 21:21
KBox Attempt Phase 2.

Apologies!
