### ISSUE TITLE
Appserver can't contact DB "No route to host in lock_may_be_available()"

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#290] opened 2015-07-07 18:09 UTC
I've noticed this several times now, from anecdotal evidence it seems to occur after I've started my Kalabox in the morning but have left it alone for a bit (not sure if my computer went to sleep in the interm). Error received:

![screen shot 2015-07-07 at 10 53 53 am](https://cloud.githubusercontent.com/assets/1153738/8553434/3ae653d8-2498-11e5-8291-18a9cd3cbb6d.png)

SSHing into the appserver container, I tried pinging my db container and got "Destination Host Unreachable" messages. After a kbox restart (which gets rid of the problem) I had no problem pinging the db container.

Definitely has similarities to #268.

**Comment by labboy0276** [comment] 2015-07-07 18:11
+1 I have received this as well lately.  I usually do a kbox restart and all is well on the app.

**Comment by pirog** [comment] 2015-07-07 18:34
Hmmm i havent seent his yet but ill def be on the lookout

On Tue, Jul 7, 2015 at 11:12 AM, John Ouellet <notifications@github.com>
wrote:

> +1 I have received this as well lately. I usually do a kbox restart and
> all is well on the app.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/290#issuecomment-119289050>.
>



-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by pirog** [comment] 2015-07-20 00:05
@labboy0276 could you research this and just post reliable steps to replicate?

**Comment by labboy0276** [comment] 2015-07-25 18:10
@pirog I think all these issues are tied into what I have been documenting on #193 

I think this all stems from the same problems, albeit it has been running ok since i cleansed my entire system of kb2 and reinstalled.  This included removing ~/.kalabox completely.

I noticed that seems to be coming up in some of the queues as well.

Thoughts?

**Comment by pirog** [comment] 2015-07-25 20:34
Yeah i think that is good intuition and kind of what i was thinking as well. @bcauldwell  possible metrics identifier issue?

**Comment by labboy0276** [comment] 2015-07-26 02:18
@pirog all systems have been normal since I did that.

**Comment by bcauldwell** [comment] 2015-07-27 18:30
I don't see any reason to think it could be an instance id problem, but
also very odd that removing ~/.kalabox is solving problems. I'd like for
someone to get themselves into this bad state, then incrementally remove
things from the ~/.kalabox folder to try and divide and conquer the culprit.

On Sat, Jul 25, 2015 at 1:34 PM, Mike Pirog <notifications@github.com>
wrote:

> Yeah i think that is good intuition and kind of what i was thinking as
> well. @bcauldwell <https://github.com/bcauldwell> possible metrics
> identifier issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/290#issuecomment-124888122>.
>



-- 
- Benjamin Cauldwell

**Comment by pirog** [comment] 2015-07-28 14:19
@bcauldwell yeah i only mention it because that was the latest thing we added into ~/.kalabox. I think we should keep this issue open until we find out the precise reason.

**Comment by labboy0276** [comment] 2015-08-09 13:01
So @pirog since you asked me to replicate and assigned this to me, I have foind the cause in thoust ~/.kalabox.  Beyond that I am not 100%, I am going to reassign to @bcauldwell and things like that.

**Comment by bcauldwell** [comment] 2015-08-19 18:32
I am unable to reproduce this bug. Maybe it's my system or setup, I don't know. If someone can help me reproduce, or get their system into that state I'll be able to troubleshoot from there. Any volunteers?

**Comment by pirog** [comment] 2015-08-19 18:32
i havent been able to replicate either

**Comment by pirog** [comment] 2015-08-24 18:11
had this sitting in sleep mode for the weekend and site is fine when i return. not sure what else to do here so closing for now.

**Closed by pirog** 2015-08-24 18:11 UTC
Labels: bug fix

**Comment by madeofpeople** [comment] 2015-09-15 16:08
@pirog 

Getting a slightly different error on 0.10.0, but also "no route to host", let me know if it's a different issue.

```PDO::__construct(): [2002] No route to host (trying to connect via   [warning]
tcp://XXXXXXXX.kbox:3306) environment.inc:546
The drush command 'features-revert-all' could not be found.  Run     [error]
`drush cache-clear drush` to clear the commandfile cache if you have
installed new extensions.```

**Comment by pirog** [comment] 2015-09-18 22:16
@madeofpeople can you provide steps to replicate? knowing what site is is on would be helpful too... can def email me that so its not public.
