### ISSUE TITLE
404 on image that exists in files/images

### ISSUE THREAD

**Issue by UTANdev** [kalabox/kalabox#205] opened 2015-06-17 12:25 UTC
After importing an existing site into Kalabox, I found that uploaded images are inaccessible — http://mtms.kbox/sites/default/files/images/summer.jpg returns a 404, even though the file does exist in *MY_APP_ROOT*\code\sites\default\files\images .

I wonder if there's a permissions problem but, since this is my first time developing on Kalabox in my native Win7 environment, I don't quite know what to look for. Is it a standard Win perms problem? Is it a KBox problem? Thanks for your help.

**Comment by labboy0276** [comment] 2015-06-17 12:32
Hello,

Can you post your kalabox.json in here?  This was I know what suggestions to give.

**Comment by UTANdev** [comment] 2015-06-17 12:53
```
{
  "appName": "mtms",
  "appPlugins": [
    "kalabox-plugin-dbenv",
    "kalabox-plugin-drush",
    "kalabox-plugin-git",
    "kalabox-plugin-php",
    "kalabox-plugin-rsync"
  ],
  "shareIgnores": [
    "sites/default/files/*",
    ".git"
  ],
  "pluginConf": {
    "kalabox-plugin-drush": {
      "drush-version": "7"
    },
    "kalabox-plugin-php": {
      "php-version": "5.3.29"
    },
    "kalabox-plugin-dbenv": {
      "settings": {
        "conf": {
          "pressflow_smart_start": 1
        }
      }
    },
    "kalabox-plugin-git": {
      "git-username": "UTAN_dev",
      "git-email": "utan_dev@utanmedia.com"
    }
  },
  "appComponents": {
    "appserver": {
      "image": {
        "name": "php-appserver",
        "srcRoot": ":appRoot:"
      },
      "proxy": [
        {
          "port": "80/tcp",
          "default": true
        }
      ]
    },
    "db": {
      "image": {
        "name": "mariadb",
        "srcRoot": ":appRoot:"
      }
    }
  }
}
```

**Comment by labboy0276** [comment] 2015-06-17 13:20
OK

Look here in the kalabox.json:

```
  "shareIgnores": [
    "sites/default/files/*",
    ".git"
  ],
```
and here:
```
"kalabox-plugin-rsync"
```
All your files are will be in a containersnow and are being ignored by syncthing.  There is no longer a sites/default/files/* folder on your local machine.  This was done due to syncthing imploding on huge file directories.  Plus you never really access the files directory locally in 92% of the time working on the site.

So all files are imported via kbox rsync now.  If you check out this fancy quick guide I wrote:
https://github.com/kalabox/kalabox/wiki/QUICK-Start---TL;DR

It explains at the end how to do the rsync portion.  Try that and see if you still get a 404.

**Comment by UTANdev** [comment] 2015-06-17 14:54
Thanks for the detailed, "teaching a man how to fish" explanation.

I'm now having trouble getting rsync to transfer the files. At first I tried to do it directly, i.e. including the remote host in rsync's SRC parameter, but couldn't get it right, so I simply tar's the files on the server, FTP'd the tarball onto my PC and extracted it to D:\UTAN\Downloads\.

What's the proper syntax to specify an rsync SRC on a different Windows drive or folder? Here's the output from my attempt:
```
C:\Users\UTAN\VirtualBox VMs\mtms\code>kbox rsync -avn "D\UTAN\Downloads\files\" sites/default/files/
info: DOCKER => Creating RUN container.
info: DOCKER => Attaching RUN container.
info: DOCKER => Starting RUN container.
Enter passphrase for /ssh/.ssh/id_rsa:
Identity added: /ssh/.ssh/id_rsa (/ssh/.ssh/id_rsa)
sending incremental file list
rsync: change_dir "/code//D\UTAN\Downloads\files" sites/default/files" failed: No such file or directory (2)

sent 12 bytes  received 12 bytes  48.00 bytes/sec
total size is 0  speedup is 0.00 (DRY RUN)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1070) [sender=3.0.9]
info: DOCKER => RUN container shutting down.
```
1) kbox asks me for an SSH passphrase, but that's the topic for [another issue](https://github.com/kalabox/kalabox-plugin-drush/issues/7).
2) How can I specify "D:\UTAN\Downloads\files\" as a source in a way that kbox will accept?

**Comment by labboy0276** [comment] 2015-06-17 15:10
KB2 shall feed you for a lifetime.

In the interim, try this:
kbox rsync -avn ~\Downloads\files\ sites/default/files/

See if that does the trick, it looks like a syntax issue obviously.

**Comment by UTANdev** [comment] 2015-06-17 18:42
Not there yet:
```
C:\Users\UTAN\VirtualBox VMs\mtms\code>kbox rsync -avn ~\Downloads\files\ sites/default/files/
info: DOCKER => Creating RUN container.
info: DOCKER => Attaching RUN container.
info: DOCKER => Starting RUN container.
Enter passphrase for /ssh/.ssh/id_rsa:
Identity added: /ssh/.ssh/id_rsa (/ssh/.ssh/id_rsa)
sending incremental file list
rsync: link_stat "/code/~\Downloads\files\" failed: No such file or directory (2)

sent 12 bytes  received 12 bytes  48.00 bytes/sec
total size is 0  speedup is 0.00 (DRY RUN)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1070) [sender=3.0.9]
info: DOCKER => RUN container shutting down.
```

Same result with `kbox rsync -avn ..\..\..\Downloads\files\ sites/default/files/`

**Comment by labboy0276** [comment] 2015-06-17 18:50
Something doesnt seem kosher with the way you are calling it:

Try

```
kbox rsync -avn ~/Downloads/files/ sites/default/files/
```

**Comment by UTANdev** [comment] 2015-06-17 18:57
Rsync doesn't recognize `~` as my home directory:
`rsync: change_dir "/code//~/Downloads/files" failed: No such file or directory (2)`
Same result whether I use the standard cmd.exe or Console2 (which is what I've been using).

**Comment by labboy0276** [comment] 2015-06-17 19:10
Yes, worth a shot, seem Windows hates that.

Let me research this a little and talk with @pirog some.

**Comment by labboy0276** [comment] 2015-06-17 19:24
Can you try this command and post the output please:

```
kbox rsync -rlvz --verbose "d\UTAN\Downloads\files\" sites/default/files/
``

**Comment by UTANdev** [comment] 2015-06-17 22:15
```
>kbox rsync -rlvz --verbose "d\UTAN\Downloads\files\" sites/default/files/
info: DOCKER => Creating RUN container.
info: DOCKER => Attaching RUN container.
info: DOCKER => Starting RUN container.
Enter passphrase for /ssh/.ssh/id_rsa:
Identity added: /ssh/.ssh/id_rsa (/ssh/.ssh/id_rsa)
sending incremental file list
rsync: change_dir "/code//d\UTAN\Downloads\files" sites/default/files" failed: No such file or directory (2)
delta-transmission disabled for local transfer or --whole-file
total: matches=0  hash_hits=0  false_alarms=0 data=0

sent 12 bytes  received 12 bytes  48.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1070) [sender=3.0.9]
info: DOCKER => RUN container shutting down.
```

**Comment by labboy0276** [comment] 2015-06-17 23:22
just for the hell of it, try this:

```
kbox rsync -rlvz "\d\UTAN\Downloads\files\" sites/default/files/
```

**Comment by UTANdev** [comment] 2015-06-18 16:04
Same result: `rsync: change_dir "/code//\d\UTAN\Downloads\files" sites/default/files" failed: No such file or directory (2)`

It seems unlikely that I would be the first Windows user trying to `kbox rsync` from a local source. Let me spin up a new app and see if it rsyncs as expected.

**Comment by labboy0276** [comment] 2015-06-18 16:30
Yes it is very odd.  @pirog any thoughts on this?

**Comment by labboy0276** [comment] 2015-06-20 19:03
One thing I will suggest is that just putting the sites/default/files dir back into the code base.  If the file directory is not that large (less then 1GB), then this is a good work around until we can resolve this odd rsync issue.

Change your shares ignore to this:
```
  "shareIgnores": [
    ".git"
  ],
```

Do a ```kbox rebuild && kbox start``` on the app and then take the file tar and put it in sites/default/files.  Monitor syncthing @ 127.0.0.1:60008 to see how it is moving along.

This should help you some in the interim.

**Comment by pirog** [comment] 2015-06-22 17:23
I am going to do some testing on Win7 later today or tomorrow so i can hopefully provide some insight here.

**Comment by pirog** [comment] 2015-07-18 18:57
So there was a bug here that stopped you from removing s/d/f from your shareignores that was fixed in the latest release.

**Comment by UTANdev** [comment] 2015-07-18 19:08
Thanks! Would that be 0.8.0? (Checking) (Sound of screeching tires) Ooo, shiny new 0.9.0. Cool! (`Watch`ing releases page)

**Comment by pirog** [comment] 2015-07-18 19:11
0.9.0 has some nice pantheon goodies if you use pantheon! def check it out.

On Sat, Jul 18, 2015 at 3:08 PM, UTAN Dev <notifications@github.com> wrote:

> Thanks! Would that be 0.8.0? (Checking) (Sound of screeching tires) Ooo,
> shiny new 0.9.0. Cool! (Watching releases page)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/205#issuecomment-122580911>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by tschet** [comment] 2015-08-21 18:40
I believe I have a related problem. I have tested multiple sites, but they all have the same issue with images. A site imported with git and a clean build both will not display images. The original images and new uploaded images are in the files directory, but images styles are not being generated. Oddly, if I turn off clean URLs everything works.

**Comment by pirog** [comment] 2015-08-21 18:47
` Oddly, if I turn off clean URLs everything works.

This is actually really helpful! thanks for the post and i think i can replicate this now.

**Comment by tschet** [comment] 2015-09-02 20:16
I had a few minutes to test this again. I can confirm labboy0276's suggestion above, moving your file directories under sites/default/ resolves the issue. In my initial testing the files and tmp directories were at the root of the site, but when I move them into the sites/default directory, my images start working.

**Closed** 2015-10-19 19:55 UTC
Labels: task
