### ISSUE TITLE
Cannot pull live database.

### ISSUE THREAD

**Issue by craigbertrand** [kalabox/kalabox#1561] opened 2016-08-31 14:57 UTC
Can't find any relevant issue.
1. Please tag your issue appropriately.

bug fix
1. Based on the issue type tag selected above please fill in the relevant section below.
# Bug Report

What is your Kalabox version and operating system?

0.13.0-beta.4 on Mac 10.11.5

Have you previously installed Kalabox? If so, what version?

Yes, I've installed Kalabox v0.13.0-beta.3

**Tell us about your bug**

I've ran the command "kbox pull -- --database=live --files=none -v"

Everything seems to work however the command is still pulling the dev database.

I am attempting to create a local clone of the live site for emergency access if pantheon goes down. I have set a cron job to do this nightly.

Any advice would be appreciated. Hopefully It is a user error.

**Comment by chrisbaptie** [comment] 2016-09-08 14:28
I am also having this issue pulling live database on Pantheon sites. This was working in an earlier version of Kalabox, I believe back when I was using v0.12.x. I noticed the issue on v0.13.0-beta.3 and hoped v0.13.0-rc.1 would resolve it, which it has not.

Running the pull command and selecting `live` as the database source appears to sit and download based on network activity. Selecting `dev` or `test` seem to work fine. Worth noting, when selecting `live` the local database remains unchanged.

**Comment by pirog** [comment] 2016-09-09 21:20
@craigbertrand @craigbertrand thats good to know. i just tried doing this on one of my sites and it seemed to work as expected. can you give more details on the nature of your site? ie is it an organization site? do you have any relevant locks or quicksilver hooks that might prevent the live database from being pulled?

@ataylorme do you know of anything on the pantheon end that might prevent someone from pulling directly from live?

i should also emphasize that pulling directly from live is probably not the best development flow and could potentially be risky.

**Comment by ataylorme** [comment] 2016-09-12 14:26
> @ataylorme do you know of anything on the pantheon end that might prevent someone from pulling directly from live?

> i should also emphasize that pulling directly from live is probably not the best development flow and could potentially be risky.

I think pulling from live to local is fine. It's something built into the workflow - as the end user or client enters new content (e.g. pages, posts) and uploads media in live you want to be able to have that latest content in other environments (dev, test, multidev, local, etc.)

This is already doable in the Pantheon dashboard via the `files/database` tab of each site environment and shouldn't be anything blocking it on our side.

**Comment by pirog** [comment] 2016-09-12 19:33
@ataylorme thanks andrew. 

@craigbertrand @chrisbaptie if there is no issue on the pantheon end then i think the most likely culprit here is that your live site might have some sort of php error that is preventing drush from bootstrapping correctly. This can happen if you are running php7 for your live site but still using something like drush 5.

**Comment by pirog** [comment] 2016-09-14 22:55
I suspect this is being caused by issues raised in #1589, going to add to that epic

**Comment by chrisbaptie** [comment] 2016-09-16 17:59
Thanks for the follow ups @pirog, appreciated.

I'll need to take a closer look at our setup, though I will keep tabs on #1589 too as it sounds like that might help.

**Comment by craigbertrand** [comment] 2016-09-16 18:07
Just getting back from vacation. I appreciate the input. I will also look at #1589 and see whats up. I don't think I have any php errors but I will also take a look at that. Thanks again.

**Comment by pirog** [comment] 2017-09-21 17:25
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!

**Closed by pirog** 2017-09-21 17:25 UTC
Labels: bug fix, pantheon app
