### ISSUE TITLE
Add `wp-cli` and other common php tooling commands to vanilla wordpress apps

### ISSUE THREAD

**Issue by Mchampsee** [kalabox/kalabox#1505] opened 2016-07-30 03:23 UTC
# Bug Report

**Tell us about your setup**

0.13.0-beta.3 on Mac OS X 10.11.3

Have you previously installed Kalabox? If so, what version?

Yes, prior releases

**Tell us about your bug**

I created a WordPress site using kalabox (i.e. a site not hosted at Pantheon) and a number of commands that are available on Pantheon sites isn't available on a directly created WordPress site.
 Example: 

> 1. Type in `kbox create wordpress`
> 2. Enter whatever in the options
> 3. Once created, type `kbox wp` and you get an error saying that its not an option.

**Tell us more**

Bug doesn't prevent me from using kbox. In addition to wp-cli, it appears that composer, mysql and php also aren't available.

**Comment by pirog** [comment] 2016-08-01 19:57
@Mchampsee going to investigate this for our next release. def want to make sure all the wordpress things work!

**Comment by pirog** [comment] 2016-08-04 04:45
@Mchampsee, so this seems to work for me. There are two immediately obvious things i can thing of that would cause this

1. After you created the site you didn't `cd` into it. You need to be inside of an app folder to see all the tools that come with it http://docs.kalabox.io/en/stable/users/cli/#kalabox-cli
2. You named your site `wp` which is a known bug #889 

That said it looks like we don't have the correct `mysql` extension installed inside of terminus so `wp-cli` commands are all failing anyway :(

**Comment by Mchampsee** [comment] 2016-08-04 18:59
@pirog - I am in the folder. It does allow me to use git, bower, grunt, gulp, node, npm and rsync. I also named the site after the client, so wasn't "wp". I've created a site using the command line as well as one using the GUI and both give me the limited set of options.

**Comment by pirog** [comment] 2016-08-04 19:01
@Mchampsee ahhh ok i see the issue here. This whole time i was thinking you were creating a pantheon site. :/ 

So, the reason you aren't seeing those things is because i dont think they are supported for wordpress. 
http://php.kalabox.io/en/stable/users/tooling/ (docs should be updated to reflect that some tools are just drupal)

perhaps we should turn this into a feature request?

**Comment by Mchampsee** [comment] 2016-08-04 19:37
@pirog - The four missing commands I noted are available if you `kbox create pantheon` and should work on a WordPress install. I would assume that wp-cli is supported by WordPress :). There is the `kbox terminus` command that I wouldn't expect to be able to use on a standalone install of WordPress.

As things stand, when you are in a Pantheon site, all commands are available to you including drush on a WordPress install and wp-cli on a Drupal install.

**Comment by pirog** [comment] 2016-08-04 19:48
@Mchampsee a pantheon app is completely separate from a normal wordpress app. 

just because you have `wp-cli` for a pantheon wordpress app it doesn't mean you can use that on different non-pantheon apps. similarly afaik `kbox terminus` does not come included with the vanilla wordpress app. indeed **each app has its own independent set of tooling commands.** 

so what you are experiencing is exactly what you should be experiencing, aka this is not a bug. that said we are down to add these additional commands so that vanilla wordpress sites also have them at their disposal. should i turn this into a feature request to do that?

**Comment by Mchampsee** [comment] 2016-08-04 20:10
Gotcha...makes sense to turn this into a feature request

**Comment by pirog** [comment] 2016-08-05 16:21
Done!

**Comment by pirog** [comment] 2017-09-21 17:32
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!

**Closed by pirog** 2017-09-21 17:32 UTC
Labels: feature, php app
