### ISSUE TITLE
Pantheon site shared via organization fails to appear in the site list

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#1264] opened 2016-04-19 21:08 UTC
Bug Report
==========

**Tell us about your setup**

v0.12.0-alpha3 on OSX

**Tell us about your bug**

1. Click "Add Pantheon Account"
2. Add credentials for an account that is part of an organization of which I am an admin, but I am NOT a team member of at least one site
3. Click on the new Pantheon account to see the site list
4. I can see sites created on my personal account, but not the sites that belong to the organization for which I'm an administrator

These sites do appear when running `kbox terminus sites list` and `terminus sites list`.

**Suggested Steps for Resolution**

- [ ] If this is a Pantheon permissions issue, update documentation
- [ ] If this is an issue with how we're interpreting Terminus data, update code.

**Comment by reynoldsalec** [comment] 2016-04-19 21:09
@drakythe originally reported this via email, let me know if I'm missing anything important in the report. I still haven't been able to reproduce the error, but there could be some caching on the Pantheon side that might not reflect changes I'm making to my site access permissions immediately.

**Comment by drakythe** [comment] 2016-04-19 22:18
Thanks, @reynoldsalec. If you guys need anymore information, screenshots, whatever. Let me know, I'm happy to provide details.

**Comment by pirog** [comment] 2016-04-19 23:10
Lots of good info in this ticket but looks like we might be missing a few things to replicate it?

**Comment by drakythe** [comment] 2016-04-20 12:41
@pirog Can I add any information to help clarify what those steps might be? Again I'm happy to run any commands and screenshot the results for you.

**Comment by drakythe** [comment] 2016-04-20 12:48
![screenshot 2016-04-14 09 18 51](https://cloud.githubusercontent.com/assets/1108374/14674912/e761ba92-06cb-11e6-9ff2-af73b2c086c5.png)
![screenshot 2016-04-14 09 19 02](https://cloud.githubusercontent.com/assets/1108374/14674916/f07e0d10-06cb-11e6-8532-41e145af435d.png)
![screenshot 2016-04-14 09 19 12](https://cloud.githubusercontent.com/assets/1108374/14674919/f42b1a84-06cb-11e6-802b-d486bc4b115b.png)
![screenshot 2016-04-14 16 51 33](https://cloud.githubusercontent.com/assets/1108374/14674922/f6d8670a-06cb-11e6-96b4-0ed107c7c27d.png)
![screenshot 2016-04-14 16 52 04](https://cloud.githubusercontent.com/assets/1108374/14674924/f8e21f14-06cb-11e6-8d48-1d1a7203bb0c.png)

I went ahead and attached the images I had used when communicating with @reynoldsalec. The first three show the relationship between my account and the website in question. The last two show what happens when I spun up a dev site attached to my Pantheon account and then check my site list in Kalabox to verify that my credentials were correct and I was receiving a site list.

**Comment by pirog** [comment] 2016-04-20 15:56
Thanks @drakythe. 

I'll try to replicate this as soon as i can and then i might have a better idea of what additional and relevant replication info might be missing.

**Comment by amklose** [comment] 2016-04-21 14:04
@drakythe If you click in to the site dashboard and click "Teams" in the top right corner, are you listed as a team member for that site? I noticed that even though I have access to all my organization's sites, only the ones I specifically add myself as a team member of show up in my Kalabox GUI when adding an app.

**Comment by drakythe** [comment] 2016-04-21 17:48
@amklose That fixed it! I was _not_ associated with it at the team level with my account, just the organization.

So I'm unsure if this is a documentation issue or an issue with Kalabox interpreted data. It seems like if I can see/operate on a site with terminus then I should be able to see/operate on it with Kalabox, I hadn't even considered that I could associate myself with the site's team and get it.

**Comment by pirog** [comment] 2016-04-27 19:08
It might be nice to get someone over on the pantheon side to confirm whether this is the expected behavior or not. 

Do you need to be explicitly on a sites's team to have access to pull it down via Kalabox?

**Comment by reynoldsalec** [comment] 2016-04-29 21:35
We recreated this now that we have some dedicated Kalabox testing accounts:

1. if you log-in as herald@kalabox.io, you'll see that kalabox-test shows up in your dashboard
2. Run `terminus auth login herald@kalabox.io`
3. Run `terminus sites list` and you'll see kalabox-test
3. Login to Kalabox as herald@kalabox.io, 'kalabox-test' doesn't show up

@pirog if I'm seeing kalabox-test after running `terminus sites list`, doesn't that mean the error is on the Kalabox side, not with Pantheon?

**Comment by pirog** [comment] 2016-04-30 00:49
So we actually hit their API directly because we may not have a terminus container yet. We should make sure the endpoint we are hitting is the same as `terminus sites list` because it seems like it clearly is not.

I'll ping JK on this.

**Comment by tsi** [comment] 2016-05-27 09:34
Same issue here, I understand that asking my clients to add me as a team member would fix the issue, but as far as they're concerned I already have access to their pantheon repo and dashboard and that was enough until we tried using Kalabox.

**Comment by pirog** [comment] 2016-08-03 15:53
So we might want to have an option to show all the sites in orgs the user belongs to.

**Comment by pirog** [comment] 2016-08-03 16:02
@ataylorme

**Comment by pirog** [comment] 2016-08-10 16:30
Not positive but wondering if this is caused by the following bug in terminus
https://github.com/pantheon-systems/terminus/issues/1135

**Comment by ataylorme** [comment] 2016-08-10 16:44
@pirog I thought you were pulling from the API directly and not Terminus for site lists?

**Comment by pirog** [comment] 2016-08-11 23:53
@ataylorme yes we are hitting the api directly. edited the comment above to reflect what i actually meant. was on the fly and just wanted to get a ref to that issue dropped into this issue!

**Comment by joshkoenig** [comment] 2016-08-23 17:13
+1 for adding org associated sites. For agencies this is going to be really important.

**Comment by pirog** [comment] 2016-08-30 02:38
Adding some RESEARCH here.

This currently does not work if you pass in all the options needed on the CLI and do it non-interactively ie

`kbox create pantheon -- --token=mike@pirog.me --site=kalabox-test --env=dev --name=test`

It fails on our direct api call to get some information about the site presumably because we need to go through the org entrypoint. **HOWEVER**, if you manually enter the required info into `kalabox.yml` ie simulating the success of the direct API call everything works peachy thereafter. 

So this is the PEMDAS here

1. Add org entrypoint to get info on a site (client.js)
2. Add CLI UX around adding an org site directly by entering the machine name
3. Add GUI UX to do the same

**Comment by pirog** [comment] 2016-08-30 02:46
@joshkoenig @ataylorme so not sure if this is the expected behavior or not but sites that you are able to access via an org (but are not in your dashboard) do not show up in the `pantheon.aliases.drushrc.php` file, however you can access similarly sensitive information for the site via `kbox terminus site connection-info`.

**Comment by joshkoenig** [comment] 2016-08-30 16:19
Let me take a look. We recently improved the way org-associated sites are found in terminus.

**Comment by joshkoenig** [comment] 2016-08-30 16:28
Yes; we recently deployed a `site-names` api endpoint. This is the quick way to get the goods on a specific site.

The pattern for getting all the sites for a user, including organizations, currently requires hitting multiple endpoints:

`users/<user-uuid>/memberships/sites  # sites you are a direct team member on`
`users/<user-uuid>/memberships/organizations  # orgs you are in`
`organizations/<org-uuid>/memberships/sites # repeat as needed across orgs`

The `/sites` commands all respect `?limit=N&start=<last-uuid>` for paging if necessary.

Happy to work with you to get PoC API calls working.

**Comment by pirog** [comment] 2016-08-30 17:28
@joshkoenig awesome. i did exactly what you just posted.

issue now is that the org sites dont show up in the `pantheon.aliases.drushrc.php` list, which we use to get the DB. that said we do also have a pure `sql` fallback method we can use for now.

**Comment by joshkoenig** [comment] 2016-08-30 17:54
Ok great. I would say it's better to use the primary api for connection info rather than drush aliases, since this is all happening per-site anyway, right?

**Comment by pirog** [comment] 2016-08-30 17:57
@joshkoenig there is another issue that documents this but we use the drush aliases because it sets up the ssh-tunnel which can pipe the DB dump back MUCH MUCH MUCH faster than directly connecting to mysql with the connection info via the api/terminus.

**Comment by pirog** [comment] 2016-08-30 21:40
OK. i think this is ready to be merged in, just waiting for the tests to pass.

**Closed** 2016-08-30 23:17 UTC
Labels: bug fix, pantheon app

**Comment by pirog** [comment] 2016-09-09 21:25
@joshkoenig just following up on your last comment here and our discussion last week. 

do/should we have a ticket or landing point for the mysql slow via connection info but fast via drush issue? makes sense for this to be on the pantheon end but wanted to make sure we could get some eyes on it as well.

**Comment by joshkoenig** [comment] 2016-09-10 00:54
@pirog yes lets make a new issue about speeding up mysql sync operations.

**Comment by pirog** [comment] 2016-09-10 01:57
Best to surface on the terminus queue? Or someplace else?
