### ISSUE TITLE
Memory Leak? Kalabox becomes unusable after an hour or so.

### ISSUE THREAD

**Issue by rovo79** [kalabox/kalabox#1323] opened 2016-05-05 18:31 UTC
I may be completely off with this, but it seems to the common denominator overtime my computer starts to slow to a halt. 

Bug Report
==========

_What version of Kalabox are you using?_
alpha4

_What operating system are you using?_
OSX 10.11.3

_Have you previously installed Kalabox? If so, what version?_
alpha3

**Tell us about your bug**

Started Kalabox, launched a website; come back several hours and my computer is barely able to respond. 

_Can you recreate this bug?_
Yes, just leave Kalabox running for hours.

_Please detail the steps we can take to replicate this bug. Be as detailed as possible._
Example: 

1. Started up Kalabox
2. Power on a Site
3. Leave computer running for a couple hours
4. Come back and try to use computer

One thing I've noticed in my Activity Monitor is a task running called 'nwjs helper'.

**Comment by pirog** [comment] 2016-05-05 18:42
@rovo79 that is troublesome if true. I usually leave kalabox on basically all the time, for multiple days at a time and havent seen this on my machine. Obviously this can vary from machine to machine which might be what is happening here.

Can you give us some details about your machine and its setup re: performance?

**Comment by rovo79** [comment] 2016-05-05 18:45
I'm having this issue on a Macbook Air and Macbook Pro. They are far from the latest computers, but figured they should be able to run this without much issue, but maybe I’m overestimating.

Macbook Air:
1.3GHZ i5
4GB ram

Macbook Pro:
2.4GHZ
8GB ram

Both on SSDs.

Both running OS X 10.11.4

Please let me know if you’d like more details.

**Comment by pirog** [comment] 2016-05-05 18:48
At the very least the macbook pro seems pretty reasonable. 

Do you have a ton of other software or services running that could be impacting this? If you use virtualization (vbox, vmware) for other things and have more than just the Kalabox2 VM running that could be an obvious performance hit.

**Comment by Steve-A-Orr** [comment] 2016-05-16 22:10
I've had the most recent alpha and the first beta freeze, if left alone for less than an hour and they must be forced to close on my Mac. The previous alpha did not do this...I might go back to it. I can provide the actual version numbers, if desired.

**Comment by pirog** [comment] 2016-05-16 22:12
@Steve-A-Orr please do! 

I'd be curious to compare the difference since there is nothing off the top of my head that would account for this.

**Comment by Steve-A-Orr** [comment] 2016-05-16 22:30
The problem versions for me are _Alpha4_ and _Beta1_ (this has been installed twice, in an attempt to fix the issue). The former broke on both my **Macbook Pro** (El Capitan) and my **Mac Pro** (Yosemite, 10.10.5); the latter was only installed on my _Mac Pro_ and is frequently freezing after non-use (with no recognized common programs open on the occurrences). The Alpha3 didn't have the same freezing issue and I was enjoying it quite immensely on both systems.

**Comment by pirog** [comment] 2016-05-16 22:39
@Steve-A-Orr, i assume you exclusively use the GUI? Do you know if this also happens if you are only using the CLI?

**Comment by Steve-A-Orr** [comment] 2016-05-16 22:45
Originally I used only the CLI. I can't remember when I was offered the chance to use the GUI, but it was recent. Since getting access, I've only been using the GUI and noticing the freeze; previous CLI versions didn't cause me problems.

**Comment by pirog** [comment] 2016-05-17 22:36
@Steve-A-Orr got it.

@rileysaurus do you have any idea what could have caused this regression? The only thing that immediately jumps out at me is having the syncthing scan interval always be 2 seconds.

**Comment by amklose** [comment] 2016-05-18 15:48
I got this warning in the CLI just now when I was trying to pull a site. Could it be related?

`(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at ReadStream.addListener (events.js:140:15)
    at ReadStream.Stream.pipe (stream.js:50:12)
    at /usr/local/bin/plugins/kalabox-engine-docker/provider/docker/docker.js.jx:334:25
    at tryCatcher (/usr/local/bin/node_modules/bluebird/js/main/util.js.jx:25:23)
    at Promise._settlePromiseFromHandler (/usr/local/bin/node_modules/bluebird/js/main/promise.js.jx:506:31)
    at Promise._settlePromiseAt (/usr/local/bin/node_modules/bluebird/js/main/promise.js.jx:580:18)
    at Promise._settlePromises (/usr/local/bin/node_modules/bluebird/js/main/promise.js.jx:696:14)
    at Async._drainQueue (/usr/local/bin/node_modules/bluebird/js/main/async.js.jx:122:16)
    at Async._drainQueues (/usr/local/bin/node_modules/bluebird/js/main/async.js.jx:132:10)
    at Async.drainQueues (/usr/local/bin/node_modules/bluebird/js/main/async.js.jx:14:14)
    at process._tickCallback (node.js:917:13)
`

**Comment by pirog** [comment] 2016-05-18 16:55
@amklose i've seen this before as well but i *think* it is unrelated to the issue here.

**Comment by pirog** [comment] 2016-05-24 17:13
Closing this in favor of #1368

**Closed** 2016-05-24 17:30 UTC
Labels: bug fix, cli
