### ISSUE TITLE
Users home directory on OSX is not located in `/Users`

### ISSUE THREAD

**Issue by davidneedham** [kalabox/kalabox#678] opened 2015-11-07 21:40 UTC
I just installed kalabox for the first time. I tried to install a Pantheon Drupal site. It ran through and installed the standard kbox tools it needs the first time it's run, and ended with the following errors:

```
Error dispatching event listeners [post-create-app]: Error running ad hoc container with kalabox/terminus:t0.9.1.: Non-zero exit code: 1 cp: cannot stat `/ssh/.kalabox/terminus/session/foo@example.com': No such file or directory
{"date":"2015-11-07 21:35:15","level":"ERROR","message":"Client error response\n[status code] 403\n[reason phrase] Forbidden\n[url] https:\/\/api.github.com\/repos\/pantheon-systems\/cli\/releases?per_page=1"}

VError: Error running ad hoc container with kalabox/terminus:t0.9.1.: Non-zero exit code: 1 cp: cannot stat `/ssh/.kalabox/terminus/session/foo@example.com': No such file or directory
{"date":"2015-11-07 21:35:15","level":"ERROR","message":"Client error response\n[status code] 403\n[reason phrase] Forbidden\n[url] https:\/\/api.github.com\/repos\/pantheon-systems\/cli\/releases?per_page=1"}

    at Object.dockerInstance.then.bind.then.then.then.catch.finally.self (/usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:735:13)
From previous event:
    at Object.use (/usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:734:11)
From previous event:
    at /usr/local/bin/lib/engine.js.jx:579:29
From previous event:
    at Object.exports.use (/usr/local/bin/lib/engine.js.jx:576:4)
    at /Volumes/AWTozer/david/kdocs/d8-module-updates/plugins/kalabox-plugin-pantheon/lib/terminus.js:109:29
    at process._tickCallback (node.js:812:13)
```

Since then I've tried a D8 site and a D7 site and I always seem to get the same errors. Any ideas how I can debug this?

**Comment by pirog** [comment] 2015-11-09 23:05
hey @davidneedham have you looked in `~/.kalabox/terminus/session/`? to see if the session we are pulling looks legit or not? I saw another error that looked like this and was the result of terminus returning an error on auth as the actual session instead of the session itself.

**Comment by davidneedham** [comment] 2015-11-09 23:14
As far as I can tell it looks legit, but I can't really be sure. I see the session, session_expire_time, user_uuid, email, and name.

Since this was my first time using Kalabox on this computer it asked me for my email and password - so I assume this session was just generated right before I did this.

**Comment by pirog** [comment] 2015-11-09 23:19
yeah that def sounds legit. 

`{"date":"2015-11-07 21:35:15","level":"ERROR","message":"Client error response\n[status code] 403\n[reason phrase] Forbidden\n[url] https:\/\/api.github.com\/repos\/pantheon-systems\/cli\/releases?per_page=1"}
` is being generated by terminus and *i think* should only show up if you are passing in a bad session. It could also happen if kbox is not sharing in your session correctly to the terminus container. are you doing anything weird with your home directory? generally we share all of `/Users/` into the VM so that we can share things like sessions and keys with specific containers.

**Comment by davidneedham** [comment] 2015-11-09 23:28
I don't believe I'm doing anything weird, but I've had to sudo more than I've expected (when installing composer, drush, etc). Could it be a permissions issue? I tried running `sudo kbox create pantheon` with no change in the result.

**Comment by pirog** [comment] 2015-11-09 23:42
oh weird. you definitely should not need to use sudo. AFAIK running sudo will probably F up your whole install since it things you are running as a different user. 

The only time it should ask for a password is during the first install. Where else are you getting this?

**Comment by davidneedham** [comment] 2015-11-10 11:10
Oh, so I am doing something weird. ;-) 

I know I need sudo whenever composer is changing things (to update or change the version of Drush being used). It looks like moving anything into `/usr/local/bin` gets permission denied, so I probably used sudo to put kbox there. I'll try moving kbox to another bin where I can access w/o sudo.

**Comment by davidneedham** [comment] 2015-11-10 12:33
I just moved kbox a a `~/bin` directory that I created, and went into `~/.bash_profile` to set up the PATH manually. The command still worked after moving it there (without sudo) but unfortunately I still get the same error I had before. Could one of the other things kbox was installing be accessing space that needs sudo?

**Comment by pirog** [comment] 2015-11-10 22:10
Yeah its likely. If you installed initially with sudo then your VB VM is owned by ROOT instead of you. I also think this would be true for syncthing and the boot2docker executable.

Have you tried doing the uninstall script (you'd probably want to try that as sudo but not positive) and then running `kbox create` without sudo?

**Comment by davidneedham** [comment] 2015-11-11 16:03
Huh, I can't actually find where I should go to run the uninstall script. if I follow the directions and do `kbox config | grep srcRoot`, it tells me where kbox is. But where should the uninstall script be?

I don't know if this is related, but when I just run `kbox config`, I see a couple sections that reference directories that don't exist. I have `/Volumes/DriveName/david/.kalabox`, but both `kalaboxRoot` and `kboxRoot` reference `/Volumes/DriveName/david/kalabox` (no period). Weird right?

**Comment by labboy0276** [comment] 2015-11-11 16:17
Hi David,

If you go here: https://github.com/kalabox/kalabox/releases

Grab the uninstall script from there and then run it.

On Wed, Nov 11, 2015 at 11:03 AM, David Needham <notifications@github.com>
wrote:

> Huh, I can't actually find where I should go to run the uninstall script.
> if I follow the directions and do kbox config | grep srcRoot, it tells me
> where kbox is. But where should the uninstall script be?
>
> I don't know if this is related, but when I just run kbox config, I see a
> couple sections that reference directories that don't exist. I have
> /Volumes/DriveName/david/.kalabox, but both kalaboxRoot and kboxRoot
> reference /Volumes/DriveName/david/kalabox (no period). Weird right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/678#issuecomment-155827173>.
>



-- 
*John Ouellet*
*Sr Developer & Support Manager*
415-470-3076
www.kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pirog** [comment] 2015-11-11 20:47
@davidneedham interesting. I assume you are using the binary version? Do you have your home folder mounted on a separate volume? Maybe that is causing some of the rage here.

**Comment by davidneedham** [comment] 2015-11-12 12:49
Thanks @labboy0276 . I ran the uninstaller and started again.

Yes - the binary. I see now from there that you only officially support OSX 10.10+. I'm running 10.9.5 - would that explain the issue I'm seeing?

And yes! My home folder is actually mounted on a separate volume.

**Comment by davidneedham** [comment] 2015-11-12 13:03
FYI: when re-installing, step 13 asked me for my admin password.

**Comment by pirog** [comment] 2015-11-16 22:16
at @davidneedham where is your separate Volume mounted? I think it needs to be in `/Users` somewhere for the B2D VB file sharing to work. 

being prompted for an admin password on those steps makes sense so that is good.

**Comment by davidneedham** [comment] 2015-11-16 22:37
I'm not sure what that means. Both drives are at `/Volumes`. One drive has only my home directory in it. The other drive has everything else.

**Comment by pirog** [comment] 2015-11-16 22:50
So by default we share all of `/Users` into the VM to share config and other things. I think if you have a symlink like

`/Users/me -> /Volumes/myvolume` 

Then we should be sharing in that volume as well. Do you know how you have the separate volume as home directory set up? With a symlink? Some other mechanism?

**Comment by davidneedham** [comment] 2015-11-17 04:05
No, not a symlink. When I first set up the OS + ssd I went into advanced settings (via System Preferences) and defined the home directory on the new drive: http://apple.stackexchange.com/questions/99298/change-users-home-directory.

**Comment by pirog** [comment] 2015-11-18 18:12
Got it. 

I'm not exactly sure the best way to handle this so ill just lay out some options.

1. We optionally discover if a users home directory is not in `/Users` and try to share that into the VM as well. I think this path would be dark and full of peril. 

2. We instruct the user to set up some sort of symlink in `/Users` something like

```
`/Users/username -> /Volume/path/to/home
```

@davidneedham I would try this second approach and see if you can get anywhere with it. In the meantime im going to leave this open so we can get some more feedback on the best resolution.

**Comment by davidneedham** [comment] 2015-11-19 02:15
Hmmm, strange. So, if I visit `/Users` I see my username there. But if I try to cd into it, I get a permission denied. I just tried sudo-ing to cd into it, but the prompt just came back - no error, no change in directory. I can `sudo ls` into the directory and see that `Library/Preferences/loginwindow.plist`exists inside of that, but nothing else.

I wonder if the OS is doing something weird here, since I set the location in the osx user settings.

**Comment by pirog** [comment] 2015-11-21 18:20
hmmm yeah im not super clear on how OSX handles this custom home directories. 

I think the first best thing to check would be if OSX actually needs /Users/username for anything anymore or if its just vestigial cruft from the initial user account setup.

**Comment by eosrei** [comment] 2015-12-03 20:46
Was just talking with @davidneedham about this.

> I just tried sudo-ing to cd into it, but the prompt just came back - no error, no change in directory. 

`cd` is a shell command, not a program. `sudo` requires a program name such as `bash`.

> I can sudo ls into the directory and see that Library/Preferences/loginwindow.plistexists inside of that, but nothing else.

Please provide the output of:
```
$ sudo ls -l /
```
Permissions seem wrong on `/Users`

Two ideas:

1. Mount the new disk at `/Users`, I wouldn't be surprised if more programs than just Kalabox expect all users to be in `/Users`. Use: https://en.wikipedia.org/wiki/Disk_Utility or edit the `/etc/fstab`

2. Kalabox should share the user's $HOME only, ignoring `/Users`.

Quick possible ~~solution~~ workaround for David's issue: 
```
$ sudo rm -rf /Users/username; sudo ln -s /Volume/path/to/home /Users/username;
```

**Comment by davidneedham** [comment] 2015-12-03 21:23
It looks like permissions on `/Users` is `drwxr-xr-x`.

Unfortunately I can't risk spending a lot of time potentially breaking and fixing my local environment right now. I'll probably just give up on this until I can start over and set everything up from scratch.

**Comment by pirog** [comment] 2015-12-05 22:06
+1 for @eosrei's proposed solutions here. 

For a little more background. 

>  I wouldn't be surprised if more programs than just Kalabox expect all users to be in /Users

Prepare to be surprised! So boot2docker, which we are using in kalabox, is actually the thing that does the file sharing so it is actually making the user must be in /Users assumption. 

We could certainly check for situations like @davidneedham's but im more leaning towards enforcing the users in /Users assumption because i think generally you are going to want to have your things set up this way in a broader-than-kalabox sense. 

@eosrei can you think of any other potential non-kalabox fails that could result in having users not in /Users?

**Comment by eosrei** [comment] 2015-12-05 22:26
> Prepare to be surprised! 

You mean: prepare to be *not* surprised! Haha! Or surprised it's not Kalabox?

>  boot2docker, which we are using in kalabox, is actually the thing that does the file sharing so it is actually making the user must be in /Users assumption. 

Is this issue fixed in docker-machine? If not, we should open an issue. I know /Users is the de facto location on OSX, but it's not guaranteed.

> can you think of any other potential non-kalabox fails that could result in having users not in /Users?

Not off the top of my head, but that's probably because users are in /home in my primary OS. :)  Either way, as proven by at least boot2docker, some OS X applications are building the user home path from `/User/ + $USER` rather than using `$HOME`.

Since a dependency is the cause at this point, it's reasonable to limited by it. It's not feasible to support every edge case.

**Comment by pirog** [comment] 2015-12-05 22:51
Lol. Maybe that should have been more like ~prepare to be surprised~. 

I don't think docker-machine handles any sharing stuff at all AFAIK but i could be VERY (and hopefully) wrong about that.

So by default B2D actually shares in all of `/Users` not `/Users/ + $USER` 
https://github.com/boot2docker/boot2docker-cli/blob/9a2606673efcfa282fb64a5a5c9e1b2f89d86fb4/virtualbox/machine.go#L131

Since B2D cli is deprecated we could actually fork and fix this pretty easily so it shares in $HOME/$USERPROFILE instead of all of /Users, could also merge in linux sharing support finally
https://github.com/boot2docker/boot2docker-cli/pull/344

**Comment by eosrei** [comment] 2015-12-05 23:08
$HOME is all that's needed, not $HOME/$USERPROFILE. $HOME is '/Users/name' on OS X and '/home/name/' on Linux.

Ha! The boot2docker [code](https://github.com/boot2docker/boot2docker-cli/blob/9a2606673efcfa282fb64a5a5c9e1b2f89d86fb4/virtualbox/machine.go#L128) has a TODO for this specific problem:
```
// TODO once boot2docker improves, replace this all with homeDir() from config.go so we only share the current user's HOME by default
```

Whatever $HOME is that's the only thing that should be shared by boot2docker & kalabox.

> I don't think docker-machine handles any sharing stuff at all AFAIK but i could be VERY (and hopefully) wrong about that.

Related: "Mount a non /Users directory as a data volume on OS X": https://github.com/docker/machine/issues/1826

**Comment by pirog** [comment] 2015-12-05 23:11
comm fail. $HOME:POSIX::$USERPROFILE:WINDOWS

**Comment by eosrei** [comment] 2015-12-05 23:12
That's makes more sense :laughing:

**Comment by pirog** [comment] 2015-12-05 23:18
So there are a few more critical issues that are in a shitty spot right now because of reliance on B2D-cli and related installer packages. 

I'm starting to feel some more energy around maybe doing the B2D/Machine switch sooner than we had talked about previously @eosrei

**Comment by eosrei** [comment] 2015-12-08 06:42
http://docs.docker.com/engine/userguide/dockervolumes/#mount-a-host-directory-as-a-data-volume

> If you are using Docker Machine on Mac or Windows, your Docker daemon has only limited access to your OS X or Windows filesystem. Docker Machine tries to auto-share your /Users (OS X) or C:\Users (Windows) directory. So, you can mount files or directories on OS X using.

>docker run -v /Users/<path>:/<container path> ...

>On Windows, mount directories using:

>docker run -v /c/Users/<path>:/<container path> ...`

>All other paths come from your virtual machine’s filesystem. For example, if you are using VirtualBox some other folder available for sharing, you need to do additional work. In the case of VirtualBox you need to make the host folder available as a shared folder in VirtualBox. Then, you can mount it using the Docker -v flag.

**Comment by pirog** [comment] 2015-12-08 21:06
I think this is further complicated because right now the B2D iso does this
https://github.com/boot2docker/boot2docker/tree/master/rootfs/rootfs/etc/rc.d

So even if we had the b2d-cli/docker-machine adding $HOME, we'd still have
to make the logic in the ISO a bit smarter.

On Mon, Dec 7, 2015 at 10:42 PM, Brad Erickson <notifications@github.com>
wrote:

>
> http://docs.docker.com/engine/userguide/dockervolumes/#mount-a-host-directory-as-a-data-volume
>
> If you are using Docker Machine on Mac or Windows, your Docker daemon has
> only limited access to your OS X or Windows filesystem. Docker Machine
> tries to auto-share your /Users (OS X) or C:\Users (Windows) directory. So,
> you can mount files or directories on OS X using.
>
> docker run -v /Users/:/ ...
>
> On Windows, mount directories using:
>
> docker run -v /c/Users/:/ ...`
>
> All other paths come from your virtual machine’s filesystem. For example,
> if you are using VirtualBox some other folder available for sharing, you
> need to do additional work. In the case of VirtualBox you need to make the
> host folder available as a shared folder in VirtualBox. Then, you can mount
> it using the Docker -v flag.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/678#issuecomment-162790517>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pirog** [comment] 2016-01-18 20:33
I'm going to close this since its a current "limitation" in b2d. Would direct any desire to support this feature over their way

**Closed by pirog** 2016-01-18 20:33 UTC
Labels: bug fix
