### ISSUE TITLE
Create Drupal Console plugin

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#581] opened 2015-10-10 18:24 UTC
Feature Request:  Drupal Console.

**Comment by pirog** [comment] 2015-10-10 20:46
+1

**Comment by mmenavas** [comment] 2015-11-05 15:50
+1. Is anyone working on this feature request? I'm currently at Drupalcamp Mexico and would like to help out.

**Comment by pirog** [comment] 2015-11-05 16:10
@mmenavas 
I don't think we were planning to do this for at least a few more sprints so it's wide open for anyone else to do. 

If you're interested in doing it i'd recommend modeling it after the drush plugin 
https://github.com/kalabox/kalabox-plugin-drush

I'd also recommend jumping on IRC #kalabox if you have any questions. I'm usually there and happy to answer for anyone down to help with the project.

**Comment by pirog** [comment] 2015-11-05 16:22
@mmenavas 
for a little more detail. once you have a plugin in a decent state (i'd literally start by just copying the drush one and renaming it) you will want to spin up a pantheon drupal 8 app and then "add" the plugin to the app. You can do this in two steps

## Install the plugin's code

You can do this a few ways

1. Go into the root directory of your app and run `npm install PLUGINNAME/PLUGINURL`.
2. Create a folder inside hte plugin directory called `kalabox-plugin-drupalconsole` and put your plugin code in there. 

Make sure that if your plugin has any node dependencies you `npm install` them in the plugin directory as well. 

## Tell the app to use the plugin 

Open up the `kalabox.json` file inside your app and tell it to use the plugin you just added by editing the `appPlugins` property

```
  "appPlugins": [
    "kalabox-plugin-git",
    "kalabox-plugin-rsync",
    "kalabox-plugin-pantheon",
    "kalabox-plugin-drupalconsole"
  ],
```

Make sense?

**Comment by mmenavas** [comment] 2015-11-05 17:27
Thank you so much @pirog! I'll give it a shot and post questions on the IRC channel should I need help.

**Comment by pirog** [comment] 2015-11-06 00:20
awesome! looking forward to MAXIMAL MAXIMO

**Comment by mmenavas** [comment] 2015-11-25 00:47
@pirog I did some initial work in a [personal repo](https://github.com/mmenavas/kalabox-plugin-drupalconsole) but there's still much more work to do.

In the meantime, I've been able to run drupal console commands (I installed it locally) on my kbox pantheon site by adding a settings.local.php file in 'code/sites/default/' where I included the db information. For example:
```
<?php
// Drupal Console requires that PHP has a default timezone set up.
date_default_timezone_set('America/Phoenix');

// Database info.
// Note: The port number changes often. To figure out what this value is, run `kbox containers`
//  from the directory of your app
$databases['default']['default'] = array(
  'driver' => 'mysql',
  'database' => 'pantheon',
  'username' => 'pantheon',
  'password' => '',
  'host' => 'myawesomesite.kbox',
  'port' => 32785,
  'prefix' => '',
  'collation' => 'utf8mb4_general_ci',
);
```

**Comment by jmolivas** [comment] 2015-11-25 02:22
looking forward to see this, @mmenavas how can I help to make this work without modifying the file?

**Comment by mmenavas** [comment] 2015-11-25 07:19
@jmolivas Ideally, we would want to install drupal console as a kalabox plugin so we can run `kbox  drupal site:status` from an app directory. See the [drush plugin](https://github.com/kalabox/kalabox-plugin-drush) as an example. I don't think anything needs to change in drupal console, but if I find something, I will let you know.

**Comment by mmenavas** [comment] 2015-11-25 07:49
I code I posted earlier breaks the site because it probably overrides the default database. The code below checks that drupal is not bootstrapped by the pantheon-appserver.

```
<?php
// Make sure the pantheon-appserver is not bootstrapping drupal
if (!isset($_ENV['PANTHEON_ENVIRONMENT'])) {
  // Drupal Console requires that PHP has a default timezone set up.
  date_default_timezone_set('America/Phoenix');

  // Database info.
  // Note: The port number changes often. To figure out what this value is, run `kbox containers`
  //  from the directory of your app
  $databases['default']['default'] = array(
    'driver' => 'mysql',
    'database' => 'pantheon',
    'username' => 'pantheon',
    'password' => '',
    'host' => 'meltmedia.kbox',
    'port' => 32785,
    'prefix' => '',
    'collation' => 'utf8mb4_general_ci',
  );
}
```

**Comment by pirog** [comment] 2015-11-26 02:42
@mmenavas @jmolivas we are doing a testing release for alpha7 but we should have time to look at this for alpha8!

**Comment by dustinleblanc** [comment] 2016-01-05 14:46
Yo folks, I got started on this too here: https://github.com/dustinleblanc/kalabox-plugin-drupal-console

I figured starting with a clean repo instead of a fork would be good.

We are going to be doing our public site on Drupal 8 on Pantheon so I figured I might as well get on it.

**Comment by pirog** [comment] 2016-01-23 00:14
hey all! we recently simplified the process of adding "tooling" containers in v0.11. I would check out https://github.com/kalabox/kalabox/wiki/Core-plugins#kalabox-cli-kalabox-cli
and see if you can adapt your work to fit into that model. Would be great for someone to post a `kalabox-compose.yml` and `cli.yml` to get this to work

**Comment by jdleonard** [comment] 2016-10-10 04:19
@pirog Not sure what the appropriate issue etiquette is here. Was this closed because Kalabox isn't going to be developing this plugin? It seems like it could be considered a high priority for Kalabox in Drupal 8 land.

For anyone looking, here's an updated link for tooling plugin documentation: http://docs.kalabox.io/en/stable/users/config/#tooling

Also for reference, I previously created https://github.com/hechoendrupal/DrupalConsole/issues/2678 requesting that Drupal Console (on the host machine) support connecting to the database using the database credentials from Kalabox.

**Comment by dustinleblanc** [comment] 2016-10-10 12:55
@jdleonard, @pirog has confirmed its on the list, just other things have had priority and everyone working on contributing it back lost interest and moved on to something else. It's up for grabs if anyone beats the Kalabox team to it I think!

**Comment by pirog** [comment] 2016-10-10 20:30
@jdleonard i think i just got a little trigger happy! reopening this.

ditto to everything @dustinleblanc said

**Comment by pirog** [comment] 2016-10-10 20:31
Also for anyone who has the courage to try this before we do. I'd recommend checking out our wraith plugin over here for inspiration. I'm also pretty sure there is an "official" drupal console container/image that could be used.
https://github.com/kalabox/wraith

**Comment by bmcclure** [comment] 2017-02-01 02:24
I'm still tweaking and testing a bit, but I followed very closely with how you implemented wraith, and created a Drupal Console plugin here:

https://github.com/bmcclure/kalabox-plugin-drupal-console

**Comment by bmcclure** [comment] 2017-02-01 02:33
Note that currently, the plugin installs Drupal Console, and you can initialize it and run commands, but it isn't actually integrating with the drupal installation yet. I'll post here again once that's resolved, but just wanted to let people know it's underway!

**Comment by bmcclure** [comment] 2017-02-01 03:04
Just a quick update, I think the plugin is fully working now. I'm currently having an issue, but it's because the version installed in my Drupal site is different than the version installed by this plugin. I'm considering forking the docker container so that we can have an updated version with the latest 1.0 RC instead of having to choose an old beta or the latest master.

**Comment by bmcclure** [comment] 2017-02-01 06:03
I'm struggling with a couple aspects of this. The drush plugin linked further up seems somewhat outdated compared with the wraith plugin, but the wraith plugin doesn't completely demonstrate how I should properly set the parameters of the task and compose yml files for something like drupal console, which more closely resembles drush than wraith in that it must be run within the context of the Drupal site.

I have my own fork of drupalconsole at Docker Hub with the latest RC tagged as 1.0: https://hub.docker.com/r/bmcclure/drupalconsole/

However, when I try and use this docker image with the config in my current plugin, I keep just getting a response such as:

```
[ERROR] Class Drupal\Core\DrupalKernel do not exists.
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
  You have requested a non-existent service "class_loader".
```

It seems like I've got a problem either mounting the code directory, or accessing it, or setting the working directory properly, but I'm not entirely sure if that's accurate, and if so, which one it is.

**Comment by jmolivas** [comment] 2017-02-01 08:19
@bmcclure how can I test this plugin, can you add steps to replicate this ?

**Comment by bmcclure** [comment] 2017-02-01 08:34
jmolivas: There are instructions in the main README file in the repository here that work: https://github.com/bmcclure/kalabox-plugin-drupal-console

Basically, you npm install that repository within your app, then add a reference to the plugin in kalabox.yml, then restart your app.

Currently it's back to working as far as allowing you to run drupal console commands, but it does not detect the site.

**Comment by bmcclure** [comment] 2017-02-01 08:52
There seems to be another issue with the drupalconsole/console docker container: I'm using "master" as the release tag, but the version reported when running `kbox drupal --version` is 1.0.0-beta4 which is really old. That could be a big part of the problem.

**Comment by bmcclure** [comment] 2017-02-01 20:00
Latest update, I built a new docker image used by the latest version of my plugin. Now it's the current release of drupal console, it works for running global commands, but I still don't have it finding the Drupal app yet.

**Comment by bmcclure** [comment] 2017-02-01 20:38
Ok, latest version of the plugin is able to connect to the site. It's using the proper directory by default as well so you don't need to specify any additional options. However, since there are no valid database credentials in settings.php, most things still fail.

Manually putting Kalabox's DB settings in settings.php makes Drupal Console start working fully, but that's not a great solution since they change when the app is rebuilt and they should only apply locally via environment variables. Trying to come up with a better solution for that.

**Comment by pirog** [comment] 2017-02-01 20:40
@jmolivas does dc have any config eg db creds that you can store in environmental variables? is that a feature you would be interested in having if not currently supported?

if you are going to be at this florida drupal camp id be down to hack on this.

**Comment by bmcclure** [comment] 2017-02-01 20:47
Also, Drupal Console appears to have a hard requirement on $settings['hash_salt'] as I had to add that value in to avoid an error while running `kbox console` commands. Ideally, that should get read from the environment as well.

**Comment by bmcclure** [comment] 2017-02-01 20:56
@pirog Commands such as `kbox drupal generate:module` work, but create files owned by `root`. Is there a common or correct way to set permissions appropriately?

**Comment by pirog** [comment] 2017-02-01 21:01
@bmcclure there are a couple ways to get around this, does also somewhat depend on the host OS, i would check out the usermap script we are using in some of the core kalabox plugins eg drush. 

FWIW, our next version of kalabox is going to revamp a lot of permission handling so we might have a much cleaner solution in a few weeks.

**Comment by bmcclure** [comment] 2017-02-01 21:10
Thanks for the tip! I noticed that usermap script but it wasn't immediately apparent to me how to use it in a new plugin. Now that I know that's the right path, I may check into that a bit further, although like you said maybe it won't matter in a few weeks anyway (that's great news btw!).

It seems like permission handling and environment variable support for configuring site settings are the two primary things this plugin needs to be considered ready for full use.

**Comment by pirog** [comment] 2017-02-01 21:12
seems like two very solvable problems. would love to bake this directly in. DC is def one of the biggest feature requests we get.

**Comment by bmcclure** [comment] 2017-02-01 21:21
@pirog One more question about the permissions issue. If I were looking to utilize the usermap script, or something like it, is there a way to do that and still use the existing docker container that has en entrypoint of `drupal`, or would there need to be a new docker container created with usermap as its entry point?

I notice drush is using the usermap script, but it's also using the "drush/drush" Docker image I thought, so I'm trying to figure out how the usermap script relates to calling that docker container.

Sorry if this question is vague, taking somewhat of a crash course in how Kalabox composes its containers and executes tasks as a result of working on this plugin :)

**Comment by pirog** [comment] 2017-02-01 21:24
Yeah you should be able to override the entrypoint in the docker compose
definition so that it uses the usermap script. At the bottom of the usermap
script it will run $@ which is the command the user passes in, so as long
as `drupal` is in the PATH then usermap should be a drop in replacement for
drupal.

**Comment by bmcclure** [comment] 2017-02-01 21:25
Thanks so much for the quick and helpful explanation! That makes a lot of sense now.

**Comment by bmcclure** [comment] 2017-02-01 22:44
@pirog Thanks to your assistance, the permissions issue is resolved in the master branch of my plugin now using the usermap script. I verified that the plugin can now generate code in the kbox app with the correct permissions.

The only thing remaining is figuring out how to get the database and hash salt settings from the included environment variables so that CD uses them.

**Comment by bmcclure** [comment] 2017-02-01 22:55
In the meantime, adding this snippet to my settings.php file is somewhat of a workaround for the environment variable issue that shouldn't interfere if the environment variables aren't defined:

```
if (isset($_ENV['DB_NAME'])) {
  $databases['default']['default'] = array(
    'driver' => 'mysql',
    'database' => $_ENV['DB_NAME'],
    'username' => $_ENV['DB_USER'],
    'password' => $_ENV['DB_PASS'],
    'host' => $_ENV['DB_HOST'],
    'port' => $_ENV['DB_PORT'],
  );

  $settings['hash_salt'] = isset($_ENV['DRUPAL_HASH_SALT']) ? $_ENV['DRUPAL_HASH_SALT'] : '';
}
```

**Comment by pirog** [comment] 2017-02-01 23:12
@bmcclure this is awesome!

 i'll def bug @jmolivas in florida in a few weeks on the env vars. in the meantime i think it is a good call to let this lie for a bit, especially with some big core changes on the horizon.

**Comment by bmcclure** [comment] 2017-02-01 23:30
Taking a cue from @mmenavas, I updated my temporary workaround code above so that it doesn't attempt to define either of those settings if we're running in a Pantheon (or presumably kalabox web) container.

**Comment by mmenavas** [comment] 2017-03-30 18:05
Hi @bmcclure! I was out of the web dev world for a while, but I'm back now. I'm currently testing out your Drupal console plugin, and I'm getting this messages when I run `kbox drupal init` after running `kbox restart -- -d`.

<img width="533" alt="drupal-console" src="https://cloud.githubusercontent.com/assets/770699/24518439/df163172-1536-11e7-8380-0ddd079a383e.png">

Is that part of the process?

**Comment by unknownterritory** [comment] 2017-05-08 02:53
@mmenavas : I believe it is, as you most likely have already found out (answering in case it may help someone else). It seems that this plugin creates the possibility of running drupal console commands within Kalabox's CLI but that the actual drupal console resources and dependencies still need to be installed through Composer. 

The suggested composer commands need to be run from the `/code` directory, where the composer.json file was previously installed. 

Then, run again `kbox drupal init` and follow the instructions.

**Comment by pirog** [comment] 2017-09-21 17:10
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!

**Closed by pirog** 2017-09-21 17:10 UTC
