### ISSUE TITLE
git_url is not defined when pull a pantheon site

### ISSUE THREAD

**Issue by ssuribhatla** [kalabox/kalabox#1262] opened 2016-04-19 19:27 UTC
Please complete the following steps. **The more steps you complete the more
likely we are to address your issue!**

1. Please review the [current list of issues](https://github.com/kalabox/kalabox/issues) to make sure you are not submitting a duplicate.
2. Please tag your issue appropriately. Please review the [tagging criteria](https://github.com/kalabox/kalabox/blob/HEAD/CONTRIBUTING.md).
3. Based on the issue type tag selected above please fill in the relevant section below.

Bug Report
==========

**Tell us about your setup**

v0.12.0-alpha3 on Windows 7.0 Profesional

**Previous Kalabox install**

the version before v0.12.0-alpha3

**Tell us about your bug**

I tried to create a pantheon site and when it is creating the site I get an error saying that cannot read property 'git_url' of undefined.

**Steps to Recreate**

![kalabox](https://cloud.githubusercontent.com/assets/18560077/14652622/f668d70c-0629-11e6-8b9c-e0b0d1dc0dab.png)

**Comment by reynoldsalec** [comment] 2016-04-19 21:00
@ssuribhatla trimmed out some of the default content to make things easier to read.

Did you enter a site name when creating your Pantheon site in the top text box?

![kalabox](https://cloud.githubusercontent.com/assets/1153738/14655292/7594b13e-0636-11e6-9af5-e46737f1faab.png)

This may be a duplicate of https://github.com/kalabox/kalabox/issues/1177

**Comment by reynoldsalec** [comment] 2016-04-19 21:18
@ssuribhatla one other question: if you had Kalabox previously installed, did you run the uninstall script for your platform before updating?

If you could also provide some steps for reproducing the error that would be great.

**Comment by pirog** [comment] 2016-04-19 23:39
@ssuribhatla i cant replicate this with the steps provided. That said i've seen this error show up a few times and it will happen if `terminus` is unable to correctly pull meta-data about your site. 

The answers to these questions will help point us in the right direction

1. Does this happen on every site you try to pull down?
2. Is this site owned by you or someone else ie an organization?
3. Is your internet connection stable?

**Comment by ssuribhatla** [comment] 2016-04-20 21:40
Hi Mike,

we have only one site in development on pantheon.

It is owned by someone else, I was able to connect and download the code from pantheon with the previous version of kalabox. It started failing with the latest version of kalabox.

Yes I have very stable internet connection.


________________________________

**Comment by pirog** [comment] 2016-04-20 21:45
Which version were you using previously? 

I don't think we changed much, if anything, re: pulling a site down in the last few versions.

**Comment by reynoldsalec** [comment] 2016-04-21 18:40
Our best guess is this is being caused by not being authenticated w/Terminus:

**Potential Steps for Recreation**

1. Logging in w/Pantheon
2. Delete session
3. Try creating site

OR

1. Log in w/Pantheon
2. Change your Pantheon password
3. Try creating site

@rileysaurus if you have time this would be good to check out.

**Comment by Soundvessel** [comment] 2016-04-21 20:43
I was having the same issue with multiple Drupal and WP Pantheon sites. After reinstall and trying on a second machine without success changing my Pantheon password seemed to do the trick.

**Comment by ssuribhatla** [comment] 2016-04-22 19:33
I have uninstalled alpha-3 version and installed alpha-2 version on the same machine. I am now able to connect to my pantheon account and download the code.




________________________________

**Comment by reynoldsalec** [comment] 2016-04-27 05:23
Ok, I think I've figured this out. It's an extension of #1177, in that validation requiring selection of an environment wasn't working (and no default environment was provided).

Full error is as follows:

```
TypeError: Cannot read property 'git_url' of undefined
kalabox.js:61 Error: TypeError: Cannot read property 'git_url' of undefined
    at Object.ensureErrorObject (file:///Applications/Kalabox.app/Contents/Resources/app.nw/src/lib/vendor/bluebird/js/browser/bluebird.js:4824:20)
    at Promise._rejectUncheckedCheckError (file:///Applications/Kalabox.app/Contents/Resources/app.nw/src/lib/vendor/bluebird/js/browser/bluebird.js:2845:22)
    at Promise._settlePromiseAt (/Applications/Kalabox.app/Contents/Resources/app.nw/node_modules/kalabox-cli/node_modules/bluebird/js/main/promise.js:579:21)
    at Promise._settlePromises (/Applications/Kalabox.app/Contents/Resources/app.nw/node_modules/kalabox-cli/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Applications/Kalabox.app/Contents/Resources/app.nw/node_modules/kalabox-cli/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Applications/Kalabox.app/Contents/Resources/app.nw/node_modules/kalabox-cli/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Applications/Kalabox.app/Contents/Resources/app.nw/node_modules/kalabox-cli/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:321:17)
kalabox.js:60 Cannot read property 'git_url' of undefined
kalabox.js:61 TypeError: Cannot read property 'git_url' of undefined
    at /Users/alec/.kalabox/apps/cvtenrollee/plugins/kalabox-plugin-pantheon/lib/pull.js:106:28
From previous event:
    at Object.pullCode (/Users/alec/.kalabox/apps/cvtenrollee/plugins/kalabox-plugin-pantheon/lib/pull.js:101:8)
    at /Users/alec/.kalabox/apps/cvtenrollee/plugins/kalabox-plugin-pantheon/lib/events.js:33:21
From previous event:
    at AsyncEvents.<anonymous> (/Users/alec/.kalabox/apps/cvtenrollee/plugins/kalabox-plugin-pantheon/lib/events.js:32:6)
    at AsyncEvents.handle (/Applications/Kalabox.app/Contents/Resources/app.nw/node_modules/kalabox-cli/lib/util/asyncEvents.js:74:19)
    at /Applications/Kalabox.app/Contents/Resources/app.nw/node_modules/kalabox-cli/lib/util/asyncEvents.js:123:19
From previous event:
    at AsyncEvents.emit (/Applications/Kalabox.app/Contents/Resources/app.nw/node_modules/kalabox-cli/lib/util/asyncEvents.js:117:18)
    at /Applications/Kalabox.app/Contents/Resources/app.nw/node_modules/kalabox-cli/lib/create.js:404:25
From previous event:
    at Object.createApp (/Applications/Kalabox.app/Contents/Resources/app.nw/node_modules/kalabox-cli/lib/create.js:402:6)
    at Object.<anonymous> (file:///Applications/Kalabox.app/Contents/Resources/app.nw/src/modules/guiEngine/sites.js:277:28)
    at processImmediate [as _immediateCallback] (timers.js:321:17)
From previous event:
    at file:///Applications/Kalabox.app/Contents/Resources/app.nw/src/modules/guiEngine/sites.js:263:19
    at file:///Applications/Kalabox.app/Contents/Resources/app.nw/src/modules/guiEngine/queue.js:47:20
    at tryCatcher (file:///Applications/Kalabox.app/Contents/Resources/app.nw/src/lib/vendor/bluebird/js/browser/bluebird.js:4589:23)
    at Function.Promise.attempt.Promise.try (file:///Applications/Kalabox.app/Contents/Resources/app.nw/src/lib/vendor/bluebird/js/browser/bluebird.js:2034:24)
    at file:///Applications/Kalabox.app/Contents/Resources/app.nw/src/modules/guiEngine/queue.js:46:24
    at tryCatcher (file:///Applications/Kalabox.app/Contents/Resources/app.nw/src/lib/vendor/bluebird/js/browser/bluebird.js:4589:23)
    at Promise._settlePromiseFromHandler (file:///Applications/Kalabox.app/Contents/Resources/app.nw/src/lib/vendor/bluebird/js/browser/bluebird.js:2695:31)
    at Promise._settlePromiseAt (file:///Applications/Kalabox.app/Contents/Resources/app.nw/src/lib/vendor/bluebird/js/browser/bluebird.js:2769:18)
    at Promise._settlePromiseAtPostResolution (file:///Applications/Kalabox.app/Contents/Resources/app.nw/src/lib/vendor/bluebird/js/browser/bluebird.js:2433:10)
    at Async._drainQueue (file:///Applications/Kalabox.app/Contents/Resources/app.nw/src/lib/vendor/bluebird/js/browser/bluebird.js:180:12)
    at Async._drainQueues (file:///Applications/Kalabox.app/Contents/Resources/app.nw/src/lib/vendor/bluebird/js/browser/bluebird.js:185:10)
    at Async.drainQueues (file:///Applications/Kalabox.app/Contents/Resources/app.nw/src/lib/vendor/bluebird/js/browser/bluebird.js:67:14)
    at Scope.$eval (file:///Applications/Kalabox.app/Contents/Resources/app.nw/src/lib/vendor/angular/angular.js:16359:28)
    at Scope.$digest (file:///Applications/Kalabox.app/Contents/Resources/app.nw/src/lib/vendor/angular/angular.js:16175:31)
    at Scope.$apply (file:///Applications/Kalabox.app/Contents/Resources/app.nw/src/lib/vendor/angular/angular.js:16467:24)
    at HTMLButtonElement.<anonymous> (file:///Applications/Kalabox.app/Contents/Resources/app.nw/src/lib/vendor/angular/angular.js:24076:23)
    at HTMLButtonElement.jQuery.event.dispatch (file:///Applications/Kalabox.app/Contents/Resources/app.nw/src/lib/vendor/jquery/dist/jquery.js:4737:27)
    at HTMLButtonElement.elemData.handle (file:///Applications/Kalabox.app/Contents/Resources/app.nw/src/lib/vendor/jquery/dist/jquery.js:4549:28)
```

@pirog + @rileysaurus does that make sense as the root cause?

If that's the case, the validation we've implemented going into next version should prevent the problem from occurring.

**Comment by reynoldsalec** [comment] 2016-04-27 17:54
The issue in my last comment is the culprit, was able to reproduce and confirmed with the team, so @ssuribhatla + @Soundvessel + @stevector we'll have the validation prevent this from happening in our next release.

**Closed** 2016-04-27 17:54 UTC

**Comment by reynoldsalec** [comment] 2016-05-04 20:27
Note that this issue only covers problems with the validation on the Pantheon Site Add form. If you're on Kalabox Alpha4 or later, please confirm that the Pantheon site add form requires all values:

![kalabox](https://cloud.githubusercontent.com/assets/1153738/15028098/e10b3246-11fb-11e6-98e7-54f3275ac334.png)

If it does and you're still getting this issue, see #1318
