### ISSUE TITLE
Website layout (CSS issue?) not working locally

### ISSUE THREAD

**Issue by saditham** [kalabox/kalabox#1816] opened 2017-06-28 18:53 UTC
Please complete the following steps. **The more steps you complete the more
likely we are to address your issue!**

1. Please review the [current list of issues](https://github.com/kalabox/kalabox/issues) to make sure you are not submitting a duplicate.
2. Please tag your issue appropriately. Please review the [tagging criteria](https://github.com/kalabox/kalabox/blob/HEAD/CONTRIBUTING.md).
3. Based on the issue type tag selected above please fill in the relevant section below.

Bug Report
==========

Kalabox 2.1.3 on WIndows 10

Have you previously installed Kalabox? If so, what version?

Yes,  Kalabox 2.1.3

**Tell us about your bug**
For some reason I do not see the local kbox site show up formatted.  I am suspecting some CSS execution is failing.  Please see the figures below which show the issue - the working one is on the actual site itself.  This issues was not there a month ago.  

Non-working Case - local:
![image](https://user-images.githubusercontent.com/1361051/27654828-131957c6-5bf8-11e7-88ec-8312a7c0d020.png)

Working Case - on the Web:
![image](https://user-images.githubusercontent.com/1361051/27654878-42117928-5bf8-11e7-9baf-bb1034b3997d.png)

Does this bug prevent you from using Kalabox?
Yes, hard to make changes to site and have them verified locally.

Feature/Enhancement Request
===========================

Please explain your request and its importance in the form of a user story.

*Example: As a Kalabox user who works with Drupal sites that have large databases, I want the option to exclude unnecessary database tables from being pulled when I update my site because I want faster "site pull" actions.*

Please provide some detail on how Kalabox can help solve this problem

*Example: Place an option on the "site pull" screen to exclude cache tables.*

**Comment by pirog** [comment] 2017-07-05 23:43
@saditham we havent changed anything on the kalabox side in quite some time. so, if it was working before there is a good change the regression was introduced in the application layer. 

if you check out the site with your browsers dev tools what are you seeing for those assets? are you getting 404s? are they trying to load in mixed mode?

**Comment by saditham** [comment] 2017-07-06 17:17
Hmm.  This is what I see in developer environment for the webpage - console messages do seem to indicate some CSS (and possibly others) were not loaded due too security reasons?
![image](https://user-images.githubusercontent.com/1361051/27923738-3f6a75b6-6234-11e7-98b7-7fe1b5e7815a.png)

Regards,
Shiva

**Comment by justinffs** [comment] 2017-07-07 20:51
Looks like an http/https/ssl issue not a kalabox issue.
What is the full URI for those files?  Can you load those files directly?
Did you google it? First google result for that error message goes here https://stackoverflow.com/questions/23688565/failed-to-load-resource-neterr-insecure-response

**Comment by pirog** [comment] 2017-09-21 17:22
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!

**Closed by pirog** 2017-09-21 17:22 UTC
