### ISSUE TITLE
Drupal site missing sessions and watchdog tables

### ISSUE THREAD

**Issue by amklose** [kalabox/kalabox#1560] opened 2016-08-31 14:32 UTC
# Bug Report

**Setup**

Mac OSX 10.11.6
Kalabox 0.13.0-beta.4

**Tell us about your bug**

I pulled a Drupal 7 multidev environment down from Pantheon via the GUI. The homepage loads fine but when I try to navigate to any other page, I get errors saying that either the pantheon.sessions table or pantheon.watchdog table or both are missing. Could it possibly be related to what was discussed in the last few comments of #1264?

I attempted to re-pull the database from the dev environment via the GUI and it had no effect.

```
PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pantheon.sessions' doesn't exist: SELECT u.*, s.* FROM {users} u INNER JOIN {sessions} s ON u.uid = s.uid WHERE s.sid = :sid; Array ( [:sid] => _fCuuK3E4YqT_9QOQ9pVR1_fJahetvFQAFGn8ndSWLs ) in _drupal_session_read() (line 102 of /code/includes/session.inc).
```

**Does this bug prevent you from using Kalabox?**

Yes

**Comment by pirog** [comment] 2016-09-09 21:22
@amklose does this happen on all your sites? i have seen this in a few circumstances but thought we had covered all the bases on it. can you give some more details about your site, specifically the drush and php versions associated with the site? 

We try to do some optimization on database pull to speed things up but this should only happen if you have a drupaly site that is runing drush 7 or up.

**Comment by pirog** [comment] 2016-09-14 22:56
I suspect this is being caused by the same underlying issues expressed in #1589 so im going to add this to that epic so we can all get on the same page for discussion

**Comment by pirog** [comment] 2017-09-21 17:25
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!

**Closed by pirog** 2017-09-21 17:25 UTC
Labels: blocker, pantheon app
