### ISSUE TITLE
Error when stopping app 0.12.0-alpha.18

### ISSUE THREAD

**Issue by jdleonard** [kalabox/kalabox#1149] opened 2016-03-22 00:18 UTC
I hit the power button for an app in the GUI and, after a very long wait with my fans spinning hard (which might not have been related), I received this error:
`Error dispatching event listeners [pre-app-stop]: Unexpected error while waiting for syncthing http://10.13.37.100:60008 to start.: operation timed out`

The app did appear to be stopped.

I then quit the GUI, which took a very long time to complete.

**Comment by pirog** [comment] 2016-03-23 21:32
Hmmm very interesting. 

Was this a one time thing or does it happen a) rarely? b) fairly consistently? c) all the time/FML MIKE? 

Is it app specific? Any ideas on how to replicate?

**Comment by jdleonard** [comment] 2016-03-23 21:55
It only happened once thus far. I've only used a single app with this version thus far. I have no repro steps :(

**Comment by pirog** [comment] 2016-03-23 21:56
Ok, good to know. I'll keep this issue open for now and hopefully we can get more feedback from other users.

**Comment by WidgetsBurritos** [comment] 2016-04-05 19:49
Moving my comments from #1199 to here, so there aren't multiple tickets opened for what to be similar items. I'm experiencing a similar issue as well:

This is a hard one to reproduce on my end, so not sure what can actually be done about it, unless the log files can give you enough context.  

Every once in a while syncthing just stops syncing. I can't exactly pinpoint anything in particular that causes it to happen.  I usually notice when `kbox git commit` tells me there aren't any changes when I know there should be. 

The `syncthing-stderr.log` has nothing in it. 

Here is some hopefully relevant info from `syncthing-stdout.log`:

> [GEJLA] 13:07:02 INFO: Paused state detected, possibly woke up from standby. Restarting in 1m0s.
> [GEJLA] 13:07:02 INFO: Local discovery (broadcast writer): write udp4: network is down
> [GEJLA] 13:08:02 INFO: Restarting
> [GEJLA] 13:08:02 OK: Exiting
> [monitor] 13:08:02 INFO: Syncthing exited: exit status 3
> [monitor] 13:08:03 INFO: Starting syncthing
> [GEJLA] 13:08:04 INFO: syncthing v0.11.26 "Aluminium Ant" (go1.4.2 darwin-amd64 default) unknown-user@syncthing-builder 2015-10-02 06:08:07 UTC
> [GEJLA] 13:08:04 INFO: My ID: GEJLAYA-YGXGC2Y-J3FFUGO-VUHE6NI-OXNAM6F-ZAEFEAA-JBLHZXY-DQ7XZQN
> [GEJLA] 13:08:04 INFO: Database block cache capacity 65536 KiB
> [GEJLA] 13:08:05 OK: Ready to synchronize greenpawup (read-write)
> [GEJLA] 13:08:05 INFO: Starting web GUI on http://0.0.0.0:60008/
> [GEJLA] 13:08:05 INFO: Starting local discovery announcements
> [GEJLA] 13:08:05 INFO: Device GEJLAYA-YGXGC2Y-J3FFUGO-VUHE6NI-OXNAM6F-ZAEFEAA-JBLHZXY-DQ7XZQN is "Davids-MacBook-Pro.local" at [dynamic]
> [GEJLA] 13:08:05 INFO: Device SOBIINK-IS2QZRK-KA23NPY-BUE6XRG-ZYUQ363-HXM2JEB-YPDNVQK-YGLIUQ7 is "SOBIINK-IS2QZRK-KA23NPY-BUE6XRG-ZYUQ363-HXM2JEB-YPDNVQK-YGLIUQ7" at [10.13.37.100]
> [GEJLA] 13:08:05 INFO: API listening on [::]:60008
> [GEJLA] 13:08:05 INFO: Established secure connection to SOBIINK-IS2QZRK-KA23NPY-BUE6XRG-ZYUQ363-HXM2JEB-YPDNVQK-YGLIUQ7 at 10.13.37.1:60515-10.13.37.100:22000
> [GEJLA] 13:08:05 INFO: Device SOBIINK-IS2QZRK-KA23NPY-BUE6XRG-ZYUQ363-HXM2JEB-YPDNVQK-YGLIUQ7 client is "syncthing v0.11.26"
> [GEJLA] 13:08:05 INFO: Device SOBIINK-IS2QZRK-KA23NPY-BUE6XRG-ZYUQ363-HXM2JEB-YPDNVQK-YGLIUQ7 name is "bdb37ebc48df"
> [GEJLA] 13:08:11 INFO: Completed initial scan (rw) of folder greenpawup
> [GEJLA] 13:08:15 INFO: No UPnP device detected
> [GEJLA] 13:26:20 INFO: Connection to SOBIINK-IS2QZRK-KA23NPY-BUE6XRG-ZYUQ363-HXM2JEB-YPDNVQK-YGLIUQ7 closed: read tcp 10.13.37.100:22000: connection reset by peer
> [GEJLA] 13:26:36 INFO: Established secure connection to SOBIINK-IS2QZRK-KA23NPY-BUE6XRG-ZYUQ363-HXM2JEB-YPDNVQK-YGLIUQ7 at 10.13.37.1:61036-10.13.37.100:22000
> [GEJLA] 13:26:36 INFO: Device SOBIINK-IS2QZRK-KA23NPY-BUE6XRG-ZYUQ363-HXM2JEB-YPDNVQK-YGLIUQ7 client is "syncthing v0.11.26"
> [GEJLA] 13:26:36 INFO: Device SOBIINK-IS2QZRK-KA23NPY-BUE6XRG-ZYUQ363-HXM2JEB-YPDNVQK-YGLIUQ7 name is "bdb37ebc48df"

I'm pretty sure `13:26` was around the time it stopped working, but I don't know for sure, as it took me a few minutes to discover it was no longer syncing. 

I'm currently running: `0.12.0-alpha.18`

[I've also attached some lines from the `kalabox.log` file from around that time period, if that provides any additional context.](https://github.com/kalabox/kalabox/files/205167/kbox.txt) (Note: my GMT offset is -5 hours as I'm in CDT)

Fortunately, If I run `kbox restart` everything goes back to normal, so I have a solution, but just figured I'd make you aware of it.

**Comment by pirog** [comment] 2016-04-09 17:58
@WidgetsBurritos do you know if syncthing itself stops or if the "sync interval" just gets very large? You can check the interval by going to `10.13.37.100:60008` and `127.0.0.01:60008` in your browser. 

I've seen something similar to this happen before but usually its when i step away from my computer for a long long time.

**Comment by WidgetsBurritos** [comment] 2016-04-10 03:59
I'm not entirely sure.  I'm not really familiar with syncthing, so I'm not entirely sure what I'm looking for.   Strangely enough, it's telling me on my `127.0.0.01:60008` that it's out of sync.  Although right now it appears to be working properly from my perspective.  I've included screenshots if that helps.

<img width="1177" alt="screen shot 2016-04-09 at 10 57 56 pm" src="https://cloud.githubusercontent.com/assets/5263371/14407997/9cc2adb6-fea6-11e5-9205-b589f3f642fb.png">
<img width="1178" alt="screen shot 2016-04-09 at 10 58 02 pm" src="https://cloud.githubusercontent.com/assets/5263371/14407998/9cc40e9a-fea6-11e5-9711-44f8d20b6f72.png">

**Comment by pirog** [comment] 2016-04-10 05:37
What files are listed as out of sync?

If you click on each folder you should see the sync interval listed. It
should be 2.

**Comment by WidgetsBurritos** [comment] 2016-04-10 05:49
Are you referring to the "rescan interval"?  That's set at 3600s, so I'm assuming that's the wrong thing, but don't see anything else marked as "sync interval".  
 
<img width="578" alt="screen shot 2016-04-10 at 12 43 01 am" src="https://cloud.githubusercontent.com/assets/5263371/14408331/d5e23f1c-feb5-11e5-9460-fe8870d324c0.png">

<img width="1188" alt="screen shot 2016-04-10 at 12 46 15 am" src="https://cloud.githubusercontent.com/assets/5263371/14408333/d5e73f94-feb5-11e5-98aa-18ee843d9871.png">

And the out of sync files, appear to be random icon files in the bootstrap base theme (which I don't think I've ever even touched, so not sure how it got "out of sync".)

<img width="930" alt="screen shot 2016-04-10 at 12 45 23 am" src="https://cloud.githubusercontent.com/assets/5263371/14408332/d5e4f7c0-feb5-11e5-9144-978d26d7303d.png">

**Comment by pirog** [comment] 2016-04-10 07:47
OK this is very helpful. The "rescan interval" should be set to 2 so 3600 would def explain why it seems to not be syncing. This is something we can address.

Re: out of sync, i *think* we've whitelisted icon files in the latest version so that should go away when you spin up new apps going forward. Good news is that these `*icon*` files are generally not important for dev.

At this point it seems like what you are describing is not the same as this issue so i would def post a new one and add in the info you've posted here.

**Comment by pirog** [comment] 2016-04-18 01:45
I think this is a duplicate of #1228

**Closed by pirog** 2016-04-18 01:45 UTC
Labels: duplicate
