### ISSUE TITLE
Database / WordPress Admin Area = Extremely Slow (unusable)

### ISSUE THREAD

**Issue by toobulo** [kalabox/kalabox#1757] opened 2016-12-30 05:06 UTC
- Kalabox 2.1.3
- Docker 1.12.5 (CPUs: 4 Memory 8.0GB)

- macOS Sierra 10.12.2
- MacBook Pro (Retina Mid 2012)
- 2.7 GHz Intel Core i7
- 16GB 1600 DDR3

- Have not installed Kalabox previously (first time)

On a fresh install of Kalabox, I'm getting extremely slow WordPress install administration areas. I pulled down an install from Pantheon and was getting 60 second + load times to view my installed plugins within the admin area.  

To rule out the possibility that it was something wrong with my install, I added a fresh new local site from Kalabox.  While much faster, It would still take over 7 seconds just to login to a fresh WP install.  It's basically unusable for me.  

This is still happening after computer rebooted, Kalabox restarted, Docker adjusted RAM settings, etc etc. No other apps open.  What could cause it to be running so slow?

**Comment by pirog** [comment] 2016-12-30 05:10
@toobulo have you tried using something like Chrome Dev Tools to see where the time is being burnt up? 

For a fresh install of WordPress these pages should load in less than a second so what you are experiencing is pretty troublesome.

**Comment by toobulo** [comment] 2016-12-30 05:21
Yeah it doesn't make any sense.  I was hoping to switch away from VVV (vagrant box) which was running just fine with no issues (yes I powered that down before booting Kalabox) - so my machine should be able to handle it.  

To me the issues seem database driven, and completely within the backend.  All pages on the front-end load extremely fast.  

Check the attached Chrome Dev tools screenshot.

![slow-kalabox](https://cloud.githubusercontent.com/assets/3487773/21560033/b02023c6-ce0c-11e6-8d11-1f2900aa78c5.jpg)

**Comment by pirog** [comment] 2016-12-30 05:35
@toobulo im actually seeing this now on a fresh WP spin up as well. I think we might have a regression on our hands.

**Comment by toobulo** [comment] 2016-12-30 05:46
Wow, thanks for responding so quickly I appreciate it.  Is it possible to download a DMG that might not have this issue?  

May or may not be related, but I was also noticing some hiccups on Ajax calls seeming to time out on the front-end as well (particularly with [WP Job Manager](https://wpjobmanager.com/)), page would load instant but you'd see a pre-loader forever, and the content would never load.

**Comment by toobulo** [comment] 2016-12-30 06:27
Looks like it is related to the current version of Docker!  I went ahead and installed their beta, **1.13.0-rc4-beta34.1 (14853)** and everything seems normal so far.

**Comment by toobulo** [comment] 2016-12-30 10:06
Working great until..  wanting to see file changes updating.  Any modifications made to WordPress template files do not update / sync - Docker 1.13.0-rc4-beta34.1 and Kalabox 2.1.3

**Comment by pirog** [comment] 2016-12-30 15:55
@toobulo good to know re: docker version. We will upgrade as soon as there is a new stable release. 

Re: file sharing: this is usually pretty reliable but there is a small subset of users that have issues still: https://github.com/kalabox/kalabox/issues/1718#issuecomment-259806036

I'd check back after these issues have been resolved since Kalabox generally is better than VVV. Seems like you are one of the lucky few helping us find the edge cases.

**Comment by pirog** [comment] 2017-09-21 17:35
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!

**Closed by pirog** 2017-09-21 17:35 UTC
