### ISSUE TITLE
Cannot upload files on Drupal 8 Windows 10

### ISSUE THREAD

**Issue by charlotte-bone** [kalabox/kalabox#1740] opened 2016-11-30 18:02 UTC
Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?

v 2.1.3 on Windows 10

Have you previously installed Kalabox? If so, what version?

Yes v 2.1.2

**Tell us about your bug**

Give a brief description of what happened, including any error messages that appeared.

After pulling down a Panthon D8 site, I cannot upload any files and get the error the file cannot be uploaded. It fails on a is_writable check, where the upload location is private://dirname

![image](https://cloud.githubusercontent.com/assets/5568828/20764278/6c4a8914-b725-11e6-8cae-e816550dfd72.png)

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

> Pull down a Pantheon D8 Site from the GUI
> Go to the site and to a form with a file upload
> Select a file to upload

I had a look in the scripts, within nginx.sh and noticed it was supposed to set the ownership, but the code and media ownership is root on my container and it doesn't let me update this. I am not familiar with Docker though so I don't know if I'm right in thinking this is the issue.

# Make sure we have correct ownership
chown -Rf www-data:www-data /code || true
chown -Rf www-data:www-data /media || true
chown -Rf www-data:www-data /php || true

![image](https://cloud.githubusercontent.com/assets/5568828/20764604/c99f60de-b726-11e6-95cf-d7a5a33b5746.png)

Does this bug prevent you from using Kalabox?

Yes

**Comment by pirog** [comment] 2016-12-01 16:27
@charlotte-bone this is a great ticket. i think i should def be able to replicate this. thanks for bringing it to our attention. 

If you restart the app does it correctly change the permissions?

**Comment by charlotte-bone** [comment] 2016-12-01 18:14
I've just restarted the app through the CLI and it still has the same permissions and error. I also tried going into the container terminal and tried running the commands there as a super user but it doesn't update the owner. I can update the owner for other folders such as backups though, so it looks like it's the folders that are symlinks?

Thanks,
Charlotte.

**Comment by pirog** [comment] 2016-12-01 18:50
@charlotte-bone the "files" directory will actually be in `/media` in the container so you might want to try editing that since presumably that is where your uploads are going.

All that said, there is an entire class of kalabox errors that deal with permission mapping fails that we are hoping to address with the upcoming 2.1.4 release. 

I'm going to try to organize all of those now.

**Comment by pirog** [comment] 2016-12-02 04:19
@charlotte-bone def not an apples to apples test but i can upload an image on a D7 Panopoly site on macOS. Will try D8 on Windows next.

**Comment by pirog** [comment] 2016-12-04 20:12
@charlotte-bone so on a vanilla D8 site i can upload an image to the out-of-the-box article content type. Thinking this might be restricted to files that are going to `private://` specifically. Can you confirm or deny that?

**Comment by ryanbarkley** [comment] 2016-12-10 14:02
@pirog I'm also having this issue with Drupal 8 pulled down from Pantheon as well as Druapl 7 not linked to Pantheon. Weird part is it appears to be intermittent. Usually doesn't work, then randomly works once, then not again. I'm getting errors like this one:

`The upload directory public://images/pods/case-studies for the file field field_pod_photo could not be created or is not accessible. A newly uploaded file could not be saved in this directory as a consequence, and the upload was canceled.`

**Comment by pirog** [comment] 2016-12-13 18:55
@ryanbarkley, interesting. I'll def try it out more than once then. Any chance you can provide some details on how you have your image field and file dirs set up so i can get as close as possible to your setup?

**Comment by ryanbarkley** [comment] 2016-12-13 19:28
@pirog As far as I know, nothing changed with my setup in between when it worked and when it didn't. I'm wondering if it has to do with how the files are synced with Windows? In this case, I had an embedded field collection on a BEAN with an image field. Directory was set to "images/pods". Site file system:

sites/default/files
sites/default/files/private
sites/default/private/temp

Hope this helps - please let me know if you'd like anything specific.

**Comment by pirog** [comment] 2016-12-16 04:36
@ryanbarkley just to confirm are you running the 2.1 or the 2.0?

**Comment by ryanbarkley** [comment] 2016-12-16 12:01
@pirog I'm running Kalabox 2.1.2.

**Comment by pirog** [comment] 2016-12-21 17:14
@ryanbarkley thanks! i'll give it a try again and see if i can replicate.

**Comment by ryanbarkley** [comment] 2017-01-11 03:39
@pirog Were you able to replicate? Please let me know if there's anything I can do to help. Right now I can't upload images using Kalabox, which really slows down the dev workflow.

**Comment by ummdorian** [comment] 2017-01-25 21:42
This issue was also mentioned in slack support chat [here](https://kalabox.slack.com/archives/powerusers/p1482942805000784).  It is an issue specific to using drupal (unsure if drupal version matters) on windows and has been an issue since the last major kalabox release.  
In attempts to recreate the issue it should be noted that if the drupal file field is set to use a new subdirectory of public:// the first file upload will work when it creates that directory but subsequent attempts to upload will not.  It should also be noted that writing to that directory is possible in other contexts than file fields, I had no problem importing files there using feeds.

**Comment by ryanbarkley** [comment] 2017-01-26 13:35
Sounds like @ummdorian has researched this much more than me, but this is consistent with my own experience. Image fields upload for the first time only, then stop working on Kalabox. If I push to Pantheon, I can upload files there and then pull back to Kalabox, but still can't upload additional images for that field in Kalabox.

**Comment by wolffereast** [comment] 2017-02-02 15:24
I'm running into the same issue. Windows 10, kalabox version 2.1.3. Downloaded a drupal 8 install from pantheon and was able to upload a single file per new directory. Dug into the linux permissions a bit through the kbox console (kbox . sudo su -) and came up with the following interesting items relating to the files/media folder permissions. This directly relates to what @charlotte-bone mentioned in the first bug report.

`# ls -la /`
![initial_root_ls](https://cloud.githubusercontent.com/assets/5454466/22554956/0e78ad6a-e930-11e6-84a2-9b1af91c51d2.png)

So both the symlink and the media files in the root are owned by root.
Checking the sites/default link shows the same
![initial_default_files_ls](https://cloud.githubusercontent.com/assets/5454466/22555063/6dfe80b6-e930-11e6-98de-d88aeece9b90.png)

Then I tried to update the permissions or the ownership of the media file or symlink with no luck. I then tried it with a couple other files and those updated with no issue
the commands
`# chown 1000:xfs media files lib home`
`# chmod 0777 media files lib home`
resulted in lib and home updating and files and media remaining unchanged
![post_root_ls](https://cloud.githubusercontent.com/assets/5454466/22555254/17acfaca-e931-11e6-9f23-7e032e486448.png)

I just created a fresh d7 install locally to check out if this was drupal version independant, and the same thing happened.
To reproduce:
Create a new local d7 install
Add an image field to one of hte content types
Add a piece of content with an image
Add a second piece of content with an image or try to change the original image - no go.

**Comment by wolffereast** [comment] 2017-02-02 18:05
Interestingly, when I add a new image profile for a multi image field that I have already loaded with images and pulled local all of the images generate the new size with no problem. Deleting the files and refreshing the page regenerates the images. The permissions on the new profile image directory are the same root:root 0755 shown above.

**Comment by ZieyaadMoses** [comment] 2017-03-31 08:55
I'm currently having the same issue. Has anyone found a fix to this?

**Comment by macronomicus** [comment] 2017-05-26 18:19
Yeah same here, after the latest windows updates now I cant even edit a node that has an image field, even if i'm not trying to upload/use an image field at all, I cant save nodes because I get form errors "The file could not be uploaded".  The current solution is to only do code updates and such locally, then do any content edits online in the pantheon dev environment.

**Comment by pirog** [comment] 2017-05-28 23:43
@macronomicus what kind of windows updates?

**Comment by wolffereast** [comment] 2017-06-01 15:28
For now I have found that setting up an S3 CDN with CORS configured gets me around the issue. Since the images are uploaded directly to the S3 instance I dont have to worry about the file permissions. I know this is the nuclear option but at least it works.

I also found that, when downloading the files, it helps if I delete the files symlink sites/default first. That avoided some oddities that I didnt document at the time but recall being frustrating

**Comment by TendoAki** [comment] 2017-06-14 12:10
Since this was marked closed/fixed I presumed there would be a fix commit in the repository.  So I checked it out - there's no fix.  What gives?

**Comment by pirog** [comment] 2017-06-14 15:06
@TendoAki this issue is not marked closed/fixed. Definitely still open.

Issues can also be closed without a fix so no guarantee there will be a commit.

**Comment by LoicLEMEUT** [comment] 2017-07-25 12:58
Hi,

I haved the same problem with Docker 17.03, Windows 10 and Drupal 8.3.5. 

I solved my problem here: https://github.com/wodby/docker4drupal/issues/29#issuecomment-316055081

I hope that can help you.

Loïc

**Comment by macronomicus** [comment] 2017-08-01 01:03
Thats nice, but it hacks core, did you submit this as an issue over on drupal.org?  Also, this wasnt a problem before the recent updates to docker and kalabox.  I get this on drupal 7 and drupal 8 sites too.  Since I use pantheon its easy enough to do any back-end file uploading serverside, and pull them down when needed, which is rare anyhow.

**Comment by LoicLEMEUT** [comment] 2017-08-01 08:05
Thanks,

In my post: https://github.com/wodby/docker4drupal/issues/29#issuecomment-316055081 , i referenced an issue of drupal.org. I know that's not a great solution, but there is a real problem on Drupal.

See my post, and see the multiple issues of Drupal org.

GL

Loïc

**Comment by pirog** [comment] 2017-09-21 17:12
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!

**Closed by pirog** 2017-09-21 17:12 UTC
Labels: bug fix
