### ISSUE TITLE
DNS issues in Windows 10 after installing kalabox?

### ISSUE THREAD

**Issue by jsibley2** [kalabox/kalabox#1487] opened 2016-07-25 15:56 UTC
I uninstalled both kalabox and docker in Windows, then ran the most recent beta2 installer.

Running kbox create pantheon -- -v in command.exe I received the following error:

info: Creating.
Creating.
info: Cleaning up.
Cleaning up.
verbose: DOCKER MACHINE ==> Running ["inspect"]
verbose: DOCKER MACHINE ==> Running ["status"]
verbose: DOCKER MACHINE ==> Running ["status"]
verbose: DOCKER MACHINE ==> Running ["status"]
verbose: DOCKER MACHINE ==> Running ["status"]
verbose: DOCKER MACHINE ==> Running ["status"]
verbose: DOCKER MACHINE ==> Running ["start"]
Error querying docker for list of containers.: operation timed out
TimeoutError: operation timed out
    at Timer.listOnTimeout [as ontimeout] (timers.js:120:15)
From previous event:
    at Object.list (C:\Program Files\Kalabox\bin\plugins\kalabox-engine-docker\provider\docker\docker.js.jx:100:6)
    at C:\Program Files\Kalabox\bin\plugins\kalabox-engine-docker\index.js.jx:84:21
From previous event:
    at Object.list (C:\Program Files\Kalabox\bin\plugins\kalabox-engine-docker\index.js.jx:83:6)
From previous event:
    at C:\Program Files\Kalabox\bin\lib\engine.js.jx:357:29

I believe I have a good internet connection. Why might I be having this problem? 

In case it makes a difference, I tried to kbox create drupal7 -- -v and also received a timeout error, but this time after 

verbose: DOCKER MACHINE ==> Running ["inspect"]
verbose: DOCKER MACHINE ==> Running ["status"]

**Comment by pirog** [comment] 2016-07-25 16:00
@jsibley2 do you have a Kalabox2 VM in VirtualBox?

**Comment by jsibley2** [comment] 2016-07-25 17:05
Yes, I have a Kalabox2 VM in VirtualBox and it is running.

**Comment by pirog** [comment] 2016-07-25 17:27
@jsibley2 do you have apps leftover from a previous install? Notably in`~/.kalabox/apps`. You might also want to check out `~/.kalabox/appRegistry.json` and see if that has any stale entries.

**Comment by jsibley2** [comment] 2016-07-25 19:39
There wasn't an app subdirectory. There also wasn't a file named appRegistry.json

I tried installing kalabox again from the installer after removing .kalabox, .docker, .terminus, and .virtualbox, in case that made a difference.

When I tried kbox create d7, I got this far:

Pulling data (busybox:latest)...
ERROR: Get https://registry-1.docker.io/v2/library/busybox/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fbusybox%3Apull&service=registry.docker.io: dial tcp: lookup auth.docker.io on 10.0.2.3:53: read udp 10.0.2.15:37286->10.0.2.3:53: i/o timeout

Is there something else I should try?

**Comment by pirog** [comment] 2016-07-25 19:49
There is another open issue dealing with DNS which might be worth looking
at

**Comment by jsibley2** [comment] 2016-07-25 23:11
Which DNS issue are you referring to? The one from Shaal?

Might it make sense to use a different DNS server during the installation process (e.g., Open DNS or Google)? If so, is there a proper way to change the DNS server? I've read that just changing resolv.conf might not be the way to do it.

Thanks.

**Comment by pirog** [comment] 2016-07-26 16:09
@jsibley2 yes that issue #1478 

So the issue is a lot of networks (ie corporate ones) will not allow you to use google or external dns so i dont think that is a doable solution. 

You can definitely hack `resolve.conf` as @shaal did in #1478 but thats not really a solution either. 

We need to figure out why VirtualBox is not sending in the correct DNS server info to the VM. Can you send me your vbox log or tell me more about how DNS is set up on your host machine?

**Comment by jsibley2** [comment] 2016-07-26 23:09
Is the vbox log the kalabox.log file from the .kalabox directory? If so, how would you like me to send it to you?

For the DNS info, is it safe and useful to copy and past the results from ipconfig /all? Is there something else you need?

Thanks.

**Comment by pirog** [comment] 2016-07-26 23:16
No. That is the kalabox.log. Here are the virtualbox docs https://www.virtualbox.org/manual/ch12.html which should contain info about how to find the log on your system. 

You can put it on gist if it doesnt contain sensitive information. otherwise you can email it to me at mike at kalabox.io

For the DNS stuff, i *think* the VB log should be sufficient

**Comment by jsibley2** [comment] 2016-07-27 14:23
In case this helps, if I disable virtualbox host-only network #2, my internet connection seems to be fine (although virtualbox won't work). If I enable it, I start losing connectivity on wifi. With #2 enabled, ipconfig release, renew, flushdns seems to help for a little bit, then I lose connectivity again and have to run those commands again.

At least, this seems to be what is happening.

**Comment by pirog** [comment] 2016-07-27 16:34
@jsibley2 do you bridge all your network connections together? 

i would enable the second VB adapter and then try removing the DNS entry for that adapter. Does your internet work after that?

**Comment by pirog** [comment] 2016-07-27 18:50
@jsibley2 so here are the two biggest differences between my working Windows log and what you provided:

**My Working vbox log on Windows**
```
00:00:00.391141          HostDnsMonitor: old information
00:00:00.391141            no server entries
00:00:00.391141            no domain set
00:00:00.391141            no search string entries
00:00:00.391141          HostDnsMonitor: new information
00:00:00.391141            server 1: 172.16.196.2
00:00:00.391141            server 2: 10.13.37.100
00:00:00.391141            domain: localdomain
00:00:00.391141            no search string entries
00:00:00.392114          HostDnsMonitorProxy::notify
```
Your logs
```
00:00:00.115006          HostDnsMonitor: old information
00:00:00.115006            no server entries
00:00:00.115006            no domain set
00:00:00.115006            no search string entries
00:00:00.115006          HostDnsMonitor: new information
00:00:00.115006            server 1: 208.67.222.222
00:00:00.115006            server 2: 208.67.220.220
00:00:00.115006            server 3: 10.13.37.100
00:00:00.115006            domain: hsd1.nj.comcast.net
00:00:00.115006            no search string entries
00:00:00.115006          HostDnsMonitorProxy::notify
```

**Comment by pirog** [comment] 2016-07-27 18:53
@jsibley2 so two things that are obvious to try out:

1.  Removing OpenDNS as your primary/secondary DNS and just use what your ISP and router provide. We might be getting a timeout because we are just running out of time before we get to DNS 3 vs DNS 2
2. Remove the Host Resolver setting from the Kalabox2 spin up. If the check above doesnt work i am down to walk you through how to set up Kalabox without the host resolver.

**Comment by pirog** [comment] 2016-07-27 22:26
@jsibley2 looks like @shaal is also using the OpenDNS servers over on his issue as well #1478

**Comment by pirog** [comment] 2016-07-27 23:00
@jsibley2 im going to close this issue as a dup of #1478. i think they are close enough and i'd like to get all the feedback and correspondence onto a single thread

**Closed by pirog** 2016-07-27 23:00 UTC
