### ISSUE TITLE
appRegistry lock file is sticking around

### ISSUE THREAD

**Issue by gremy** [kalabox/kalabox#1426] opened 2016-06-29 19:44 UTC
Bug Report
==========

I tried upgrading from ```0.12.0-beta1``` to ```0.13.0-alpha.1``` on Ubuntu Mate 16.04.
If I try to run ```kbox version```, or ```kbox list```, or some other command I get this error:

```
Unhandled rejection Error: /home/gremy/.kalabox/appRegistry.json already locked!
    at /usr/share/kalabox/bin/lib/app/registry.js.jx:285:13
    at acquireLock (/usr/share/kalabox/bin/lib/app/registry.js.jx:282:4)
    at actionApp (/usr/share/kalabox/bin/lib/app/registry.js.jx:331:10)
    at Serializer.<anonymous> (/usr/share/kalabox/bin/lib/app/registry.js.jx:386:12)
    at /usr/share/kalabox/bin/lib/util/serializer.js.jx:33:17
    at /usr/share/kalabox/bin/lib/util/serializer.js.jx:31:23
    at Serializer.enqueue (/usr/share/kalabox/bin/lib/util/serializer.js.jx:29:18)
    at exports.registerApp (/usr/share/kalabox/bin/lib/app/registry.js.jx:384:21)
    at /usr/share/kalabox/bin/lib/app.js.jx:181:5
    at _create (/usr/share/kalabox/bin/lib/app.js.jx:180:4)
    at exports.create (/usr/share/kalabox/bin/lib/app.js.jx:237:12)
    at Promise.map.concurrency (/usr/share/kalabox/bin/lib/app.js.jx:279:14)
    at /usr/share/kalabox/bin/lib/app.js.jx:277:20
    at Object.exports.list (/usr/share/kalabox/bin/lib/app.js.jx:276:4)
    at Object.<anonymous> (/usr/share/kalabox/bin/bin/kbox.js.jx:225:21)
    at process._tickCallback (node.js:917:13)
    at Function.Module.runMain (module.js:882:11)
    at main (/usr/share/kalabox/bin/bin/kbox.js.jx:223:4)
    at Object.<anonymous> (/usr/share/kalabox/bin/bin/kbox.js.jx:248:1)
    at Module._compile (module.js:619:26)
    at readX (module.js:1645:5)
    at Object.Module._extensions..jx (module.js:2102:10)
    at Module.load (module.js:440:36)
    at Function.Module._load (module.js:405:12)
    at Module.require (module.js:475:17)
    at require (module.js:493:17)
    at Object.<anonymous> (_jx_source:17:3)
    at Module._compile (module.js:619:26)
    at Module.load (module.js:449:12)
    at Function.Module._load (module.js:405:12)
    at Function.Module.runMain (module.js:871:12)
    at startup (node.js:485:18)
    at node.js:1604:3
```

It gets fixed temporarily if you delete ```appRegistry.json.lock```, but it comes back again after a few commands.

**Comment by RobLoach** [comment] 2016-06-29 20:12
After upgrading via the .dev....

```
➜  greenbiz  kbox version
0.13.0-alpha.1
```

**Comment by pirog** [comment] 2016-06-29 22:40
So i think what we want to do here is remove the lock mechanism since that is pretty jank and replace it with serialized access to the file. 

@gremy i think the issue you are having here is because you have a lot of possibly stale kalabox apps lying around and the new version is trying to do a lot of read/write to the appRegistry to sync things up.

**Comment by gremy** [comment] 2016-06-30 12:04
@pirog that is probably the case. Cuz I do have a lot of kbox apps.

**Comment by pirog** [comment] 2016-06-30 22:17
@gremy so i looked into this a bit more and i can actually replicate. Must be a regression. That said it looks like we already serialize access to the appRegistry but the old lock code is still in there. Should be pretty easy to fix but probably won't get to it till next week. 

That said, removing the lock file when it happens is a sufficient albeit annoying workaround for now.

**Comment by RobLoach** [comment] 2016-07-01 17:33
Ran into this today as well. Can try moving this update in and re-testing.

**Comment by pirog** [comment] 2016-07-02 22:24
Seems to work for me but i'd like to test it a bit more before merging in. Once we do that we should be able to offer the fix in the latest dev build.

**Closed** 2016-07-09 04:45 UTC
Labels: bug fix
