### ISSUE TITLE
File Syncing from native OS > Kalabox intermittent

### ISSUE THREAD

**Issue by pi-ron** [kalabox/kalabox#1718] opened 2016-11-09 02:17 UTC
Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?

v2.1.1 on OS X 10.11.6

Have you previously installed Kalabox? If so, what version?

Yes, all of them.

**Tell us about your bug**

When I edit a file on my local drive ie. `~/Kalabox/app-name/code/sites/all/themes/theme_name/gulpfile.js` it doesn't get recognised by Kalabox, unless I stop and start the app.

Give a brief description of what happened, including any error messages that appeared.

1. I edited my themes gulpfile, added a new task:

``````
gulp.task('compass-nodesass', function()
{
    return gulp.src('assets/sass/**/*.scss')
      .pipe(sass({ importer: compass }).on('error', sass.logError))
      .pipe(gulp.dest('./stylesheets'));

});
``````
2. Attempt to run my new gulp task using kbox command `kbox gulp compass-nodesass`

3. Log tells me that task is not in my gulpfile

``````
$ kbox gulp compass-nodesass                                                      ⬡ 5.12.0 [±update ●●]
[02:01:41] Using gulpfile /code/sites/all/themes/theatre_royal/gulpfile.js
[02:01:41] Task 'compass-nodesass' is not in your gulpfile
[02:01:41] Please check the documentation for proper gulpfile formatting
``````
4. Stop app
5. Start app
Task found

Does this bug prevent you from using Kalabox?

To a point, yes.  Stopping & starting an app every time I change a file isn't ideal.

**Comment by pi-ron** [comment] 2016-11-09 21:00
Following further work yesterday,  I feel like this may be intermittent.

There were definitely times when no local changes to files were being synced to Kalabox, and I would have to restart the app to get them picked up.

There were also times when changes were being picked up, and a restart was not required.

I know this is a very vague comment, but if there is anything else I can do to help diagnose please let me know.

**Comment by pirog** [comment] 2016-11-10 19:27
@pi-ron this should be fairly reliable. It IS worth mentioning that if you are bounding back and forth between `kbox gulp` and `gulp` that you might run into some issues esp if you are compiling and relying on OS specific stuff.

**Comment by pi-ron** [comment] 2016-11-10 21:00
@pirog I've been running `kbox gulp` exclusively, however, making changes to the gulpfile on my local.

**Comment by pirog** [comment] 2016-11-11 18:40
I think for most things this should work pretty well.

**Comment by wildkatana** [comment] 2016-11-20 04:21
I experienced this today as well. Restarting the app caused the files to sync up again properly.

**Comment by wildkatana** [comment] 2016-11-21 06:48
Following up on this, I haven't been able to get my Kalabox to sync the files automatically ever. So it's not intermittent for me, it's just always an issue.

Restarting my app every time I make a file change makes Kalabox basically unusable for me. :/

**Comment by zurack** [comment] 2016-11-21 20:19
Just as @wildkatana mentioned above, I've never gotten Kalabox to sync file automatically. But now it's worse than before. I used to be able to restart the app to fix it, but now that does nothing.

I installed the latest version of Kalabox last week. Pulled down a pantheon site, did some work on Friday but could not see any CSS changes locally. This morning (Monday) I open up Kalabox and the changes I made there on Friday are appearing. But now I can't get any CSS changes to appear again. Caching is turned off, I clear caches in Drupal, I restart Kalabox, restart browser, etc. No changes appearing. When I click the Code button in Kalabox I can see that the files have been saved, so even with an app restart why is Kalabox not pulling those updated CSS files?

**Comment by pi-ron** [comment] 2016-11-22 00:27
@wildkatana Are you using the latest version with native docker?

I mentioned in title intermittent, surprisingly It's been over a week now since I've had this issue occur. But, I understand your frustration too, when I posted it I was having to restart my app every time I made a change.

**Comment by wildkatana** [comment] 2016-11-22 03:24
@pi-ron I'm using the latest Kalabox version (updated last week). I had an issue during install where it said I had to uninstall Bluestacks first, because apparently Docker for Mac doesn't play nicely with it. So I uninstalled that first, then continued.

My docker version is Version 1.12.3 (13776)
<img width="627" alt="screen shot 2016-11-22 at 11 23 17 am" src="https://cloud.githubusercontent.com/assets/325023/20509777/18f0dafa-b0a6-11e6-8b6c-023cddc997b0.png">

I'm also experiencing a weird bug where clicking the 'Terminal' button doesn't do anything. Not sure if that's related or not...

I've tried restarting Docker multiple times, restarting Kalabox, restarting my computer, but nothing seems to help.

**Comment by pirog** [comment] 2016-11-24 23:34
The file sync is actually pretty reliable and stable at this point so im a little skeptical of that as the culprit. 

I'm guessing the most likely culprit is that you guys have caching or something like CSS aggregation enabled. A good test you can do to check if file sharing is actually working is to rewrite `index.php` with something like "hello world" and see if that change shows up in the browser. 

There are other factors that might impact file sharing but these are just theoretical 

1. You aren't putting your apps in either `/Users`, `/Volumes`, `/private` or `tmp`. (these are the default locations shared by Docker and you can add more via their GUI)
2. You have your home mounted on an external disk or network drive
3. You have a REALLY REALLY old computer that is just to slow to run kalabox

**Comment by wildkatana** [comment] 2016-11-25 01:17
Editing index.php was my first thought as well, and it exhibited the same behaviour. I'm quite certain it's not caching. My sites are inside of the Users directory as well. And my Mac is one of the higher end ones and only a couple years old.

Any other ideas of things I can check? Maybe the file sync service just isn't running? How can I check that and restart it if needed?

**Comment by pirog** [comment] 2016-11-25 01:26
`docker ps -a` should list all your containers and the container you want to look for is `APPNAME_unison_1`. 

Specifically you'll want to see if it's running and then check out its logs `docker logs APPNAME_unison_1` to see if you can see any notable errors. 

Other potential things that could mess with this:

1.  If you have a VERY large repository, either in raw size or quantity of files. This would be a repo on the order of 1GB. 
2. If you are using Pantheon's nested docroot feature which is not supported yet
3. Using lots of symlinks in your repo

**Comment by wildkatana** [comment] 2016-11-25 01:38
Thanks Mike. This is a brand new Drupal 7 site from Pantheon. I did add a lot of new modules to it before syncing it down, but it's mostly just the standard ones (Views, Panels, CTools, Pathauto, etc). It's certainly not 1 gb. 

I checked if the unison container is running and it is. I checked the logs and the last time it updated was a couple days ago:

```
UNISON 2.49.543 (OCAML 4.02.3) started propagating changes at 08:40:32.49 on 22 Nov 2016
[BGN] Updating file .git/index from /kalashare/code to /code
[END] Updating file .git/index
[BGN] Copying properties for .git/objects/a1/0c548ceb929d27b0e5d2d51b549646b84f87c1 from /kalashare/code to /code
[END] Copying properties for .git/objects/a1/0c548ceb929d27b0e5d2d51b549646b84f87c1
[BGN] Copying properties for .git/objects/pack/pack-4bd9673fb10f8efc46f1ef0e2a603cc69e90fcf8.pack from /kalashare/code to /code
[END] Copying properties for .git/objects/pack/pack-4bd9673fb10f8efc46f1ef0e2a603cc69e90fcf8.pack
[BGN] Updating file .idea/workspace.xml from /kalashare/code to /code
[END] Updating file .idea/workspace.xml
[BGN] Copying sites/default/settings.php from /kalashare/code to /code
[END] Copying sites/default/settings.php
UNISON 2.49.543 (OCAML 4.02.3) finished propagating changes at 08:40:32.51 on 22 Nov 2016
Saving synchronizer state
Synchronization complete at 08:40:32  (5 items transferred, 0 skipped, 0 failed)
Looking for changes
Reconciling changes
Nothing to do: replicas have not changed since last sync.
```

I tried editing the index.php file, both in my editor, then again from vim on the command line, but I didn't see any updates triggered in unison after checking the logs again. It occurred to me that all of the syncing I see are from kalashare/code to /code. I'm editing the files in /code and expecting them to sync to the docker container. Is that correct? What are the files in kalashare/code? Should I be editing those instead?

**Comment by pirog** [comment] 2016-11-25 01:57
The sync is bi-directional. `kalashare/code` is the mount from your Mac and `/code` is your mount inside the container. This is what it looks like for me directly after i edit `index.php` inside of my kalabox app.

```
Nothing to do: replicas have not changed since last sync.
Looking for changes
Reconciling changes
changed  ---->            index.php                                     
Propagating updates
UNISON 2.49.543 (OCAML 4.02.3) started propagating changes at 01:55:48.20 on 25 Nov 2016
[BGN] Updating file index.php from /kalashare/code to /code
[END] Updating file index.php
UNISON 2.49.543 (OCAML 4.02.3) finished propagating changes at 01:55:48.20 on 25 Nov 2016
Saving synchronizer state
Synchronization complete at 01:55:48  (1 item transferred, 0 skipped, 0 failed)
Looking for changes
Reconciling changes
Nothing to do: replicas have not changed since last sync.
```

Where are you editing your files locally? Have you edited your `kalabox.yml` file at all?

**Comment by wildkatana** [comment] 2016-11-25 05:01
@pirog my settings.php file is just a blank file (I had to put it there so that kbox drush would work):

```
<?php

// Nothing here

```

I tried restarting my app and then it synced properly once it restarted:

```
Contacting server...
Looking for changes
Reconciling changes
Propagating updates
changed  ---->            .git/index                                    
changed  ---->            .idea/workspace.xml  
changed  ---->            index.php  
changed  ---->            sites/all/themes/mobile_responsive_theme/templates/page.tpl.php  
UNISON 2.49.543 (OCAML 4.02.3) started propagating changes at 04:55:40.00 on 25 Nov 2016
[BGN] Updating file .git/index from /kalashare/code to /code
[END] Updating file .git/index
[BGN] Updating file .idea/workspace.xml from /kalashare/code to /code
[END] Updating file .idea/workspace.xml
[BGN] Updating file index.php from /kalashare/code to /code
[END] Updating file index.php
[BGN] Updating file sites/all/themes/mobile_responsive_theme/templates/page.tpl.php from /kalashare/code to /code
[END] Updating file sites/all/themes/mobile_responsive_theme/templates/page.tpl.php
UNISON 2.49.543 (OCAML 4.02.3) finished propagating changes at 04:55:40.02 on 25 Nov 2016
Saving synchronizer state
Synchronization complete at 04:55:40  (4 items transferred, 0 skipped, 0 failed)
Looking for changes
Reconciling changes
Nothing to do: replicas have not changed since last sync.
```

I then tried editing a file again and it didn't pick up the changes :/ It appears that somehow it is only detecting the changes when the app is restarted and not afterwards.

The files I am editing are in ~/Kalabox/APPNAME/code

Is that correct? That's how I've done it before and it seemed to always work.

I have a vagrant setup running docker on the same machine. Could that be interfering? I tried halting it with vagrant halt and restarting the Kalabox app but it didn't seem to help...

**Comment by pirog** [comment] 2016-11-25 05:10
@wildkatana, requirement of drush straight up. Not exclusive to `kbox drush`.

Don't think vagrant should interfere and seems like that is the case based on your test. One thing to verify is whether the `unison` container continues to run after that initial app start. If the process closes after that first run it would certainly explain what you are seeing. 

Is this happening on ALL your apps? Have you tried destroying/recreating any of them?

**Comment by wildkatana** [comment] 2016-11-25 05:50
@pirog I tried spinning up a new D8 kalabox app (not pantheon) and it is exhibiting the same behavior. I checked the containers and unison is running, but busybox (data_1), drush_1, and cli_1 are all not running. They exited(0) right after the app started. Is that normal?

**Comment by pirog** [comment] 2016-11-25 05:59
Yes, that is the correct state of those things.

My guess at this point is that something else you've got installed is messing with how `osxfs` (which is how Docker for Mac does file sharing) is sharing file events into the Docker VM. It also could be possible that that service is not even running.

For more background on what we do: We set unison to listen for the file events provided by `osxfs` and then perform a sync when one happens. This allows us to get around the currently dismal performance of using `osxfs` straight up. 

Googling "`osxfs` not working" turned this up which looks worth trying
https://forums.docker.com/t/com-docker-osxfs-is-not-running/15757/8

**Comment by wildkatana** [comment] 2016-11-25 08:49
Well, I've spent about as much time as I can on this for now. 

I tried reinstalling Docker, Resetting to Factory Defaults, using the Beta version, back to official version, restarting computer, etc. Nothing has worked.

I installed fswatch to see if the inotify events are actually being fired and they are. Not really sure what else I can do...

**Comment by pirog** [comment] 2016-11-25 16:09
@wildkatana yeah thats definitely no good. My best recommendation at this point would be to wait until there is a new version of Kalabox that ships with an updated Docker for Mac. I suspect this is an issue around their `osxfs` implementation since that is still in development but could be anything at this point.

In the meantime there are a few more things we can check to help isolate the issue more when you have time.

1. Make sure the `fsevents` are actually being received inside the unison container. 

You can "ssh" into it with `docker exec -i -t APPNAME_unison_1 bash`

```bash
apt-get install inotify-tools 
inotifywait -rme modify,attrib,move,close_write,create,delete,delete_self /kalashare
# Might have to wait a bit for it to watch all files
```

Change index.php on your Mac, should then see something like this output in the terminal

```bash
inotifywait -rme modify,attrib,move,close_write,create,delete,delete_self /kalashare
Setting up watches.  Beware: since -r was given, this may take a while!

Watches established.
/kalashare/code/ ATTRIB index.php
/kalashare/code/ MODIFY index.php
/kalashare/code/ ATTRIB index.php
/kalashare/code/ MODIFY index.php
/kalashare/code/ ATTRIB index.php
/kalashare/code/ MODIFY index.php
```

2. Make sure when you edit a file it shows up in the unison container eg edit `index.php` and then run `docker exec -i -t APPNAME_unison_1 cat /kalashare/code/index.php`. This should happen even if the `fsevents` are not working.

3. What are you using to edit your files locally?

4. Open up Docker for Mac and run the diagnosis to see if everything checks out.

**Comment by pi-ron** [comment] 2016-12-01 22:53
First class support 👍

**Comment by Steve-A-Orr** [comment] 2016-12-02 18:46
I don't know if you want to keep this open or create a new issue...I'm having similar issues with OS 10.10.5, Kalabox 2.1.1, and Docker 1.12.3 version. The only way I can get my local code to go to Pantheon is to use the CLI with a Git commit/push. (This is with attempts both before and after rebooting of Kalabox; with both the local site running and not running.) This Git process, of course, isn't pushing my DB changes either.

I'm considering bringing up a clean Pantheon DEV environment just to test with Kalabox. I believe that the last version of Kalabox pushed successfully. On a related note, is there a preferred time to Push/Pull code/database using the UI--for example with the local instance running or not?

**Comment by Steve-A-Orr** [comment] 2016-12-02 18:55
...and now after rebooting Kalabox once more, followed by pushing while instance is running, the code and DB changes made it into Pantheon. (This is using their Multidev feature, BTW.) Intermittent push capabilities, for sure.

**Comment by pirog** [comment] 2016-12-02 18:59
Hey @Steve-A-Orr, this issue is actually about syncing files from your HOST to the CONTAINER, not about pushing to pantheon so you might want to open a new ticket for the issue you are experiencing.

**Comment by mixxmac** [comment] 2016-12-30 09:43
Hi... I've been having this problem also (using OSx 10.11.6, Docker for Mac 1.12.5, Kalabox 2.1.3).

I tried running inotifywait in the unison container, and don't see any notifications after watches established... and changing index.php.

My computer is running low on disk space, so not sure if that is part of the problem. Also, when I run docker ps... there's often some old unison containers still running from previous days when I was using Kalabox.

Wondering if this is a problem with osfx... if it could be fixed by uninstalling/re-installing osfx? Or if I had it installed before installing Kalabox... if there is more than one copy installed... maybe the wrong one is running?

**Comment by pirog** [comment] 2016-12-30 15:49
@mixxmac sounds like you have the most recent and stable osxfs. I would remove the old unison containers with `docker rm -f CONTAINER_NAME`. 

I would guess the problem is with `osxfs` since that is a pretty new tech and `unison` has been around for a long time and is generally pretty stable and reliable. Here are a couple things to consider

1. Uninstalling Docker and then Reinstalling Docker
2. Checking out the Docker issue queues for relevant `osxfs` issues
3. Are you using something like an external drive that might be hard to get the fs events from?
4. If you have your code on your macOS then we know unison worked at least once. I assume you have your code inside of the `code` folder?

**Comment by toobulo** [comment] 2016-12-30 18:11
One thing consistent on my end, is if I pull down a fresh install within Kalabox - changing files manually works fine until I run an NPM INSTALL within that directory ([JointsWP](http://jointswp.com/) wordpress starter theme).

After I run that  command (even before running Gulp Watch), you can say forget it to any changes being synchronized again- including a "Hello World" index.php.  Closed / reopened app, etc etc. nada.  

I've tried prepending "kbox" to my npm / gulp commands, but that is the slowest thing ever and assuming technically I shouldn't have to - as I'm just wanting to run within my own file system as usual, correct?

**Comment by toobulo** [comment] 2016-12-30 18:51
Instead of running NPM / Gulp on my theme, I just tested [Codekit](http://codekitapp.com) app to listen for CSS changes - and everything works perfect.  

My issues with files not being synchronized / updated seem completely related to running NPM on in my theme folder.  

Docker 1.13.0-rc4-beta34.1
Kalabox 2.1.3

**Comment by mixxmac** [comment] 2016-12-31 09:41
@pirog... thanks for the response!

1. I used Docker for Mac to reset to factory defaults
2. In the Docker issue queues one of the osxfs issues said this might work (I'll try full uninstall/reinstall) next time
3. Not using an external drive or anything, but have been running out of disk space sometimes (before wiping out all the docker images that were there)
4. Code is inside of the code folder, but unison syncs seem to copy from container to host only (until restarting the app)
5. Not using another solution that might be hijacking folder sharing (like Vagrant/VVV)

I noticed that inotifywait gave notifications when the app (WP) made changes to files (e.g. if I uploaded an image). But, editing any files in the code directory didn't generate any notifications, but the changes show up in the container after restarting the WP app.

**Comment by mixxmac** [comment] 2016-12-31 09:46
Docker diagnostics look ok...
Docker for Mac: version: 1.12.5 (3e6f00c1d)
OS X: version 10.11.6 (build: 15G1004)
logs: /tmp/9C1E260B-4181-4EC1-B128-436DACB831D1/20161231-093128.tar.gz
[OK]     vmnetd
[OK]     dns
[OK]     driver.amd64-linux
[OK]     virtualization VT-X
[OK]     app
[OK]     moby
[OK]     system
[OK]     moby-syslog
[OK]     db
[OK]     env
[OK]     virtualization kern.hv_support
[OK]     slirp
[OK]     osxfs
[OK]     moby-console
[OK]     logs
[OK]     docker-cli
[OK]     menubar
[OK]     disk

**Comment by mixxmac** [comment] 2016-12-31 10:35
I think this problem might have been caused by having the kalabox directory in lower case. I noticed when I listed the apps using the kbox list command, all the apps were in the ~/Kalabox folder... but the directory I had in my home directory was named "kalabox".

I renamed the directory "Kalabox", and restarted the computer. At the moment the syncs seem to be working now (i.e. changes from the container to the host seem to be happening now).

Hopefully that's all that's needed to fix this issue.

**Comment by wildkatana** [comment] 2017-01-06 03:32
@mixxmac Thanks for your experiences and insight. I too had my apps in a 'kalabox' (lowercase) folder. I tried changing it to 'Kalabox' and restarting, but it didn't solve the issue for me.

So it must be something else I think.

@pirog you mentioned:

"Are you using another solution that might be hijacking folder sharing like Vagrant/VVV?"

I am using Vagrant for another dev environment. What's the best way to check for conflicts?

**Comment by chrisgross** [comment] 2017-01-25 21:25
I am also having this issue. Simple code changes to say, a custom module or theme, do not work unless I stop and start the site.

**Comment by mixxmac** [comment] 2017-01-29 16:21
Things have been working well for me recently... until now.

I was working on a Drupal app for a couple of days without any issues, then all of a sudden I started having problems with new modules and themes that I tried to add... not showing up in Drupal after copying them to the site.

The Unison containers for the apps I'm working on seem to be having problems and they keep restarting.

I ran `docker logs` on one of the unison containers, and it looks like the problems started with a permission error when I tried to edit the setting.php file...

`[END] Copying sites/all/modules/views/views.module
[BGN] Copying sites/all/modules/views/views.tokens.inc from /kalashare/code to /var/www/html
[END] Copying sites/all/modules/views/views.tokens.inc
[BGN] Copying sites/all/modules/views/views_export from /kalashare/code to /var/www/html
[END] Copying sites/all/modules/views/views_export
[BGN] Copying sites/all/modules/views/views_ui.info from /kalashare/code to /var/www/html
[END] Copying sites/all/modules/views/views_ui.info
[BGN] Copying sites/all/modules/views/views_ui.module from /kalashare/code to /var/www/html
[END] Copying sites/all/modules/views/views_ui.module
[BGN] Copying sites/default/settings.php from /var/www/html to /kalashare/code
Failed: Error in copying locally:
Permission denied [open(/kalashare/code/sites/default/.unison.settings.php.e5abde42933c3042ffe0facd0f7fd7aa.unison.tmp)]
100%  00:00 ETAFailed [sites/default/settings.php]: Error in copying locally:
Permission denied [open(/kalashare/code/sites/default/.unison.settings.php.e5abde42933c3042ffe0facd0f7fd7aa.unison.tmp)]
UNISON 2.49.543 (OCAML 4.02.3) finished propagating changes at 18:11:27.06 on 28 Jan 2017
Saving synchronizer state
Synchronization incomplete at 18:11:27  (105 items transferred, 0 skipped, 1 failed)
  failed: sites/default/settings.php
Looking for changes
Reconciling changes
         <---- new file   sites/default/settings.php
Propagating updates
UNISON 2.49.543 (OCAML 4.02.3) started propagating changes at 18:11:28.11 on 28 Jan 2017
[BGN] Copying sites/default/settings.php from /var/www/html to /kalashare/code
Failed: Error in copying locally:
Permission denied [open(/kalashare/code/sites/default/.unison.settings.php.e5abde42933c3042ffe0facd0f7fd7aa.unison.tmp)]
100%  00:00 ETAFailed [sites/default/settings.php]: Error in copying locally:
Permission denied [open(/kalashare/code/sites/default/.unison.settings.php.e5abde42933c3042ffe0facd0f7fd7aa.unison.tmp)]
UNISON 2.49.543 (OCAML 4.02.3) finished propagating changes at 18:11:28.11 on 28 Jan 2017
Saving synchronizer state
Synchronization incomplete at 18:11:28  (0 items transferred, 0 skipped, 1 failed)
  failed: sites/default/settings.php
Looking for changes
         <---- new file   sites/default/settings.php
Reconciling changes
Propagating updates
UNISON 2.49.543 (OCAML 4.02.3) started propagating changes at 18:11:33.09 on 28 Jan 2017
[BGN] Copying sites/default/settings.php from /var/www/html to /kalashare/code
Failed: Error in copying locally:
Permission denied [open(/kalashare/code/sites/default/.unison.settings.php.e5abde42933c3042ffe0facd0f7fd7aa.unison.tmp)]
100%  00:00 ETAFailed [sites/default/settings.php]: Error in copying locally:
Permission denied [open(/kalashare/code/sites/default/.unison.settings.php.e5abde42933c3042ffe0facd0f7fd7aa.unison.tmp)]
UNISON 2.49.543 (OCAML 4.02.3) finished propagating changes at 18:11:33.09 on 28 Jan 2017
Saving synchronizer state
Synchronization incomplete at 18:11:33  (0 items transferred, 0 skipped, 1 failed)
  failed: sites/default/settings.php`

The latest messages in the logs shows problems recognizing any changes and not being able to make the updates...

`UNISON 2.49.543 (OCAML 4.02.3) finished propagating changes at 19:09:02.33 on 28 Jan 2017
Saving synchronizer state
Synchronization incomplete at 19:09:02  (1 item transferred, 0 skipped, 1 failed)
  failed: sites/all/themes/shiny
Looking for changes
Reconciling changes
new file ---->            sites/all/themes/shiny/template.php
new dir  ---->            sites/all/themes/shiny/templates
Propagating updates
UNISON 2.49.543 (OCAML 4.02.3) started propagating changes at 19:09:03.71 on 28 Jan 2017
[BGN] Copying sites/all/themes/shiny/template.php from /kalashare/code to /var/www/html
Failed: The source file /kalashare/code/sites/all/themes/shiny/template.php
has been modified but the fast update detection mechanism
failed to detect it.  Try running once with the fastcheck
option set to 'no'.
[BGN] Copying sites/all/themes/shiny/templates from /kalashare/code to /var/www/html
 66%  00:00 ETAFailed [sites/all/themes/shiny/template.php]: The source file /kalashare/code/sites/all/themes/shiny/template.php
has been modified but the fast update detection mechanism
failed to detect it.  Try running once with the fastcheck
option set to 'no'.
[END] Copying sites/all/themes/shiny/templates
UNISON 2.49.543 (OCAML 4.02.3) finished propagating changes at 19:09:03.73 on 28 Jan 2017
Saving synchronizer state
Synchronization incomplete at 19:09:03  (1 item transferred, 0 skipped, 1 failed)
  failed: sites/all/themes/shiny/template.php
Looking for changes
new file ---->            sites/all/themes/shiny/template.php
Reconciling changes
Propagating updates
UNISON 2.49.543 (OCAML 4.02.3) started propagating changes at 19:09:04.76 on 28 Jan 2017
[BGN] Copying sites/all/themes/shiny/template.php from /kalashare/code to /var/www/html
100%  00:00 ETAFailed [sites/all/themes/shiny/template.php]: The source file /kalashare/code/sites/all/themes/shiny/template.php
has been modified but the fast update detection mechanism
failed to detect it.  Try running once with the fastcheck
option set to 'no'.
Failed: The source file /kalashare/code/sites/all/themes/shiny/template.php
has been modified but the fast update detection mechanism
failed to detect it.  Try running once with the fastcheck
option set to 'no'.
UNISON 2.49.543 (OCAML 4.02.3) finished propagating changes at 19:09:04.77 on 28 Jan 2017
Saving synchronizer state
Synchronization incomplete at 19:09:04  (0 items transferred, 0 skipped, 1 failed)
  failed: sites/all/themes/shiny/template.php
Looking for changes
Reconciling changes
Nothing to do: replicas have not changed since last sync.
Looking for changes
Reconciling changes
Nothing to do: replicas have not changed since last sync.
Looking for changes
Reconciling changes
Propagating updates`

When I tried to attach to the container, I get an error that the container is restarting...

`docker exec -i -t d206567aeedd bash
Error response from daemon: Container d206567aeeddf01adba28a5749663f3f0ac49f969222d771c6b97ae315070f48 is restarting, wait until the container is running`

**Comment by smitterko** [comment] 2017-03-29 00:42
I just wanted to add in my 2 cents and say thank you to toobulo because not running npm within my theme folder is the only thing that worked for me in my local dev environment. I tried so many different cache disabling techniques within Drupal & my settings.local.php file, using drush to clear my cache, editing the kalabox.yml file to only 'listen' to my theme folder, kbox npm start within the theme folder, etc etc.

Manually making a change to my css file worked after stopping npm in the theme folder. I think I will use PHPStorm's file watcher for now. Maybe this will help someone else.

Docker Version 17.03.0-ce-mac2
Kalabox 2.1.3

**Comment by tbenice** [comment] 2017-06-16 18:59
Docker v: 17.03.1-ce-mac12
Kalabox: 2.1.3

I experience semi frequent EXTREMELY FRUSTRATING incidents where changes to files within a Kalabox drupal site fail to appear in the site until i restart the app AND docker. The first time i only tried rebooting my mac which also worked, but restarting docker seems to as well.

All confidence aside, @pirog, there is still an issue with Kalabox. As im sure you can understand, im not at all interested in tinkering with the app to make it work. The product is supposed to speed my development not force me to waste my time troubleshooting it. I suspect i might have to abandon it which sucks because it has promise.

I hope this issue can be addressed seriously in the near future!

**Comment by pirog** [comment] 2017-06-16 19:06
@tbenice this is a known issue that impacts some users. it is fairly well documented (with workarounds) both on the kalabox and docker side.

**Comment by tbenice** [comment] 2017-06-16 19:09
Thanks fantastic. I've looked through this thread and don't see any documentation. Can you plz put links in here for folks like me who get to this thread? 

Thanks!

**Comment by pirog** [comment] 2017-09-21 17:23
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!

**Closed by pirog** 2017-09-21 17:23 UTC
